-- =============================================================================
-- Neon Visuals — Seed Data
-- 11 collections, Bucket A (17 SKUs) + representative B–K products, festivals.
-- No vendor seeding (vendor management is handled offline).
-- Prices are stored for internal use only.
-- =============================================================================

-- ---------- Buckets ----------------------------------------------------------
INSERT INTO buckets (code, name, slug, description, purpose, primary_buyer, asp_range_min, asp_range_max, icon, sort_order, seo_title, seo_description, is_active) VALUES
('A', 'Welcome & Onboarding', 'welcome-onboarding', 'Day-1 kits that create instant emotional ownership and desk presence.', 'Make Day 1 unforgettable', 'HR Manager', 199, 4999, 'PackageOpen', 1, 'Welcome & Onboarding Gifts for New Employees | Neon Visuals', 'Premium personalised onboarding kits that make new hires feel seen on Day 1. Name-first design, handcrafted packaging.', true),
('B', 'Milestone & Anniversary', 'milestone-anniversary', 'Recognition pieces that turn tenure into ritual and collectible memory.', 'Celebrate tenure and growth', 'HR/People Ops', 499, 7999, 'CalendarHeart', 2, 'Work Anniversary & Milestone Gifts | Neon Visuals', 'Celebrate work anniversaries and milestones with premium personalised recognition awards and keepsakes.', true),
('C', 'CEO & Leadership Recognition', 'ceo-leadership', 'Top-down recognition that feels direct, expensive, and memorable.', 'Visible recognition from the top', 'CEO/Founder', 999, 14999, 'Crown', 3, 'CEO & Leadership Recognition Gifts | Neon Visuals', 'Boardroom-grade recognition gifts and leadership awards that signal status and intention.', true),
('D', 'Festive & Seasonal', 'festive-seasonal', 'High-volume, occasion-specific festive gifting for teams and clients.', 'Festival celebrations done right', 'Admin/HR', 299, 5999, 'Sparkles', 4, 'Corporate Diwali & Festive Gifts | Neon Visuals', 'Premium festive corporate gifting for Diwali, New Year and seasonal celebrations. Personalised and camera-ready.', true),
('E', 'Client Appreciation', 'client-appreciation', 'High-ASP gifting that protects relationships and closes future revenue.', 'Strengthen business relationships', 'Sales/BD', 499, 9999, 'Handshake', 5, 'Client Appreciation & Corporate Gifts | Neon Visuals', 'Premium client appreciation gifts that strengthen relationships and close deals.', true),
('F', 'Experience Kits', 'experience-kits', 'Multi-item flagship experience kits that tell a complete story.', 'Complete themed gift experiences', 'HR/Culture Team', 1999, 9999, 'Gift', 6, 'Premium Experience Gift Kits | Neon Visuals', 'Flagship multi-item experience kits with a complete narrative arc, designed for unforgettable unboxing.', true),
('G', 'Tech-Forward & Digital', 'tech-forward', 'Modern tech-integrated gifts that are measurable and shareable.', 'Modern tech-integrated gifts', 'HR/IT', 799, 7999, 'Cpu', 7, 'Tech-Forward & Digital Corporate Gifts | Neon Visuals', 'Smart, tech-integrated corporate gifts with QR, NFC and digital layers that keep gifting alive.', true),
('H', 'Sustainability & Eco', 'sustainability-eco', 'Eco-conscious gifting that is real, beautiful, and never preachy.', 'Eco-conscious gifting', 'CSR/HR', 299, 4999, 'Sprout', 8, 'Sustainable & Eco-Friendly Corporate Gifts | Neon Visuals', 'Premium sustainable corporate gifts that are genuinely eco-conscious and beautifully made.', true);

-- ---------- Bucket A — Welcome & Onboarding (17 SKUs) -----------------------
INSERT INTO products (sku, bucket_id, name, slug, tagline, description, who_is_it_for, insight, wow_score, cogs, price_single, price_bulk_25, price_bulk_100, margin_percent, lead_time_days, rush_lead_time_days, moq, materials, personalization_types, occasions, archetypes, tags, recommended_packaging, is_featured, is_bestseller, is_new, sort_order) VALUES
('NV-A01', (SELECT id FROM buckets WHERE code='A'), 'Engraved Copper Bottle', 'engraved-copper-bottle', 'A daily ritual that carries your name', 'Double-wall copper bottle with minimal branding and strong daily utility, laser-engraved with the recipient''s name.', 'Every new joiner', 'A good bottle becomes habit, and habit is a retention signal.', 8, 380, 999, 899, 799, 58, 7, 4, 10, ARRAY['copper','powder-coated'], ARRAY['laser_engrave']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['achiever','builder']::employee_archetype[], ARRAY['desk-test','daily-use','instagram-ready'], 'standard', true, true, false, 1),
('NV-A02', (SELECT id FROM buckets WHERE code='A'), 'Name-Engraved SS Tumbler', 'name-engraved-ss-tumbler', 'Keep it hot, keep it personal', 'Insulated stainless-steel tumbler engraved with the recipient''s name for the desk and the commute.', 'New joiners and hybrid workers', 'Drinkware stays in view all day, quietly reinforcing belonging.', 7, 280, 799, 699, 649, 60, 7, 4, 10, ARRAY['stainless-steel'], ARRAY['laser_engrave']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['minimalist','connector']::employee_archetype[], ARRAY['desk-test','daily-use'], 'standard', false, false, false, 2),
('NV-A03', (SELECT id FROM buckets WHERE code='A'), 'Welcome Notebook A5 Hardbound', 'welcome-notebook-a5-hardbound', 'The quietest, most-used onboarding asset', 'Premium A5 hardbound notebook with name debossing and a welcome note insert.', 'Analysts, PMs, operators', 'The notebook is the quietest but most used onboarding asset.', 6, 180, 599, 499, 449, 64, 10, 5, 25, ARRAY['paper','faux-leather'], ARRAY['deboss','print']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['scholar','builder']::employee_archetype[], ARRAY['daily-use'], 'standard', false, false, false, 3),
('NV-A04', (SELECT id FROM buckets WHERE code='A'), 'Personalised Desk Name Plate', 'personalised-desk-name-plate', 'A status object from Day 1', 'Clean desk or wall plaque with name, role and join date — a status object, not just onboarding swag.', 'Founders, leadership, high-potential hires', 'This becomes a status object, not just an onboarding object.', 8, 220, 699, 599, 549, 65, 5, 3, 5, ARRAY['acrylic','wood'], ARRAY['laser_engrave','uv_print']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['achiever']::employee_archetype[], ARRAY['desk-test','status'], 'premium', true, false, false, 4),
('NV-A05', (SELECT id FROM buckets WHERE code='A'), 'Engraved Bamboo Pen + Box', 'engraved-bamboo-pen-box', 'A classic that sits on a desk for years', 'Bamboo pen with name engraving in a premium gift box.', 'All onboarding kits', 'A pen is a classic because it still sits on a desk years later.', 6, 200, 649, 549, 499, 66, 7, 4, 15, ARRAY['bamboo'], ARRAY['laser_engrave']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['minimalist','scholar']::employee_archetype[], ARRAY['eco','desk-test'], 'standard', false, false, false, 5),
('NV-A06', (SELECT id FROM buckets WHERE code='A'), 'Welcome Canvas Tote Bag', 'welcome-canvas-tote-bag', 'Useful merch that actually gets used', 'Sturdy canvas tote with a tasteful name or team print.', 'Conferences and onboarding', 'Useful merch gets used; that is the real metric.', 5, 170, 549, 449, 399, 66, 10, 5, 25, ARRAY['canvas'], ARRAY['print']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['connector','explorer']::employee_archetype[], ARRAY['daily-use','eco'], 'budget', false, false, false, 6),
('NV-A07', (SELECT id FROM buckets WHERE code='A'), 'Premium Personalised Mouse Pad', 'premium-personalised-mouse-pad', 'Small surface, daily touchpoint', 'Stitched-edge mouse pad with personalised print for the desk setup.', 'Remote-first and desk roles', 'Daily friction removal is underrated gifting.', 5, 120, 399, 349, 299, 65, 5, 3, 10, ARRAY['fabric','rubber'], ARRAY['print','sublimation']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['builder','minimalist']::employee_archetype[], ARRAY['desk-test','daily-use'], 'budget', false, false, false, 7),
('NV-A08', (SELECT id FROM buckets WHERE code='A'), 'Engraved Wooden Coaster Set 4pc', 'engraved-wooden-coaster-set-4pc', 'Desk-ready and quietly premium', 'Set of four engraved wooden coasters in a holder.', 'All onboarding kits', 'Desk drinkware accessories are cheap to make and easy to remember.', 7, 240, 699, 599, 549, 62, 10, 5, 15, ARRAY['wood'], ARRAY['laser_engrave']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['root','minimalist']::employee_archetype[], ARRAY['desk-test','eco'], 'standard', false, false, false, 8),
('NV-A09', (SELECT id FROM buckets WHERE code='A'), 'Welcome Hoodie Embroidered', 'welcome-hoodie-embroidered', 'Belonging you can wear', 'Soft premium hoodie with embroidered name or team mark — membership, not merch.', 'Startups with strong culture', 'People wear what signals belonging, not what screams branding.', 8, 480, 1399, 1199, 1099, 61, 12, 7, 25, ARRAY['cotton-fleece'], ARRAY['embroidery']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['connector','creator']::employee_archetype[], ARRAY['wearable','instagram-ready'], 'premium', true, false, false, 9),
('NV-A10', (SELECT id FROM buckets WHERE code='A'), 'Welcome Polo T-Shirt', 'welcome-polo-t-shirt', 'Team identity, tastefully done', 'Premium polo with subtle name or team embroidery.', 'Culture-led teams', 'Wearable recognition signals belonging without shouting branding.', 7, 320, 999, 849, 799, 64, 10, 5, 25, ARRAY['pique-cotton'], ARRAY['embroidery','dtf']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['connector']::employee_archetype[], ARRAY['wearable'], 'standard', false, false, false, 10),
('NV-A11', (SELECT id FROM buckets WHERE code='A'), 'Desk Succulent in Engraved Pot', 'desk-succulent-engraved-pot', 'A living welcome', 'Low-maintenance succulent in a name-engraved pot with a care card.', 'Culture-led companies', 'Plants create an emotional anchor and a visible care ritual.', 7, 250, 799, 699, 649, 66, 7, 4, 10, ARRAY['terracotta','plant'], ARRAY['laser_engrave']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['root','creator']::employee_archetype[], ARRAY['desk-test','eco'], 'standard', false, false, true, 11),
('NV-A12', (SELECT id FROM buckets WHERE code='A'), 'Personalised Laptop Sticker Set', 'personalised-laptop-sticker-set', 'Identity on the lid', 'A curated set of personalised die-cut stickers.', 'Engineering and design teams', 'Small personalisation is cheap, fast, and emotionally legible.', 5, 80, 299, 249, 199, 70, 3, 2, 20, ARRAY['vinyl'], ARRAY['uv_print']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['creator','builder']::employee_archetype[], ARRAY['quick-ship'], 'budget', false, false, false, 12),
('NV-A13', (SELECT id FROM buckets WHERE code='A'), 'Wooden Phone Stand Engraved', 'wooden-phone-stand-engraved', 'Premium on a worktable', 'Engraved wooden phone stand that looks premium on a desk.', 'Hybrid workers and sales hires', 'It is small, personal, and stays in view all day.', 7, 180, 549, 449, 399, 64, 7, 4, 10, ARRAY['wood'], ARRAY['laser_engrave']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['minimalist','builder']::employee_archetype[], ARRAY['desk-test','eco'], 'standard', false, false, false, 13),
('NV-A14', (SELECT id FROM buckets WHERE code='A'), 'Leather Keychain Initials', 'leather-keychain-initials', 'A small daily carry', 'Genuine/faux leather keychain embossed with initials.', 'Every new joiner', 'Daily-carry objects create repeated touchpoints.', 5, 130, 449, 379, 349, 68, 7, 5, 20, ARRAY['leather'], ARRAY['emboss']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['minimalist']::employee_archetype[], ARRAY['daily-use'], 'budget', false, false, false, 14),
('NV-A15', (SELECT id FROM buckets WHERE code='A'), 'Seed Paper Welcome Card', 'seed-paper-welcome-card', 'A welcome you can plant', 'Plantable seed-paper welcome card with a personal note.', 'Eco-conscious onboarding', 'It links a welcome message to an actual sustainability story.', 4, 60, 199, 169, 149, 67, 5, 3, 50, ARRAY['seed-paper'], ARRAY['print']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['root','creator']::employee_archetype[], ARRAY['eco','quick-ship'], 'budget', false, false, false, 15),
('NV-A16', (SELECT id FROM buckets WHERE code='A'), 'Engraved SS Bottle 750ml', 'engraved-ss-bottle-750ml', 'Hydration, handled', 'Large 750ml stainless-steel bottle engraved with the recipient''s name.', 'Every new joiner', 'A good bottle becomes habit, and habit is a retention signal.', 7, 300, 899, 799, 749, 63, 7, 4, 10, ARRAY['stainless-steel'], ARRAY['laser_engrave']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['achiever','explorer']::employee_archetype[], ARRAY['daily-use','desk-test'], 'standard', false, false, false, 16),
('NV-A17', (SELECT id FROM buckets WHERE code='A'), 'Personalised Ceramic Mug', 'personalised-ceramic-mug', 'The morning ritual, named', 'Ceramic mug with name print for the desk and the pantry.', 'All onboarding kits', 'Desk drinkware is cheap to make and easy to remember.', 6, 160, 499, 429, 399, 65, 7, 4, 15, ARRAY['ceramic'], ARRAY['sublimation','uv_print']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['connector','minimalist']::employee_archetype[], ARRAY['desk-test','daily-use'], 'standard', false, false, false, 17);

-- ---------- Bucket B — Milestone & Anniversary ------------------------------
INSERT INTO products (sku, bucket_id, name, slug, tagline, description, who_is_it_for, insight, wow_score, cogs, price_single, price_bulk_25, price_bulk_100, margin_percent, lead_time_days, rush_lead_time_days, moq, materials, personalization_types, occasions, archetypes, tags, recommended_packaging, is_featured, is_bestseller, is_new, sort_order) VALUES
('NV-B01', (SELECT id FROM buckets WHERE code='B'), '1-Year Acrylic Award', '1-year-acrylic-award', 'Year one, recognised', 'First-anniversary award with clean typography and a date lockup.', '1-year anniversary', 'Year one needs recognition without looking overly expensive.', 8, 420, 1190, 1090, 990, 65, 6, 3, 10, ARRAY['acrylic'], ARRAY['uv_print','laser_engrave']::personalization_type[], ARRAY['work_anniversary_1']::occasion_type[], ARRAY['achiever']::employee_archetype[], ARRAY['award','desk-test'], 'premium', true, false, false, 1),
('NV-B02', (SELECT id FROM buckets WHERE code='B'), '5-Year Leather Journal', '5-year-leather-journal', 'Grown-up and permanent', 'Volume-numbered leather journal with a restrained anniversary mark.', '5-year anniversary', 'Five years should feel grown-up and permanent.', 7, 565, 1590, 1490, 1390, 64, 7, 5, 10, ARRAY['leather','paper'], ARRAY['emboss','deboss']::personalization_type[], ARRAY['work_anniversary_5']::occasion_type[], ARRAY['scholar','minimalist']::employee_archetype[], ARRAY['premium','keepsake'], 'premium', false, true, false, 2),
('NV-B03', (SELECT id FROM buckets WHERE code='B'), '10-Year Crystal Trophy', '10-year-crystal-trophy', 'Boardroom-level for a decade', 'Flagship decade trophy with premium crystal engraving.', '10-year anniversary', 'Ten years deserves something that looks boardroom-level.', 9, 1210, 3490, 3290, 2990, 65, 9, 5, 10, ARRAY['crystal'], ARRAY['laser_engrave']::personalization_type[], ARRAY['work_anniversary_10']::occasion_type[], ARRAY['achiever']::employee_archetype[], ARRAY['award','status','keepsake'], 'flagship', true, false, false, 3),
('NV-B04', (SELECT id FROM buckets WHERE code='B'), 'Milestone Hoodie', 'milestone-hoodie', 'Wearable recognition', 'Hoodie with the tenure year embroidered into the design.', 'Culture-led companies', 'Wearable recognition has a better shelf life than trophies.', 8, 700, 1690, 1490, 1290, 60, 7, 5, 10, ARRAY['cotton-fleece'], ARRAY['embroidery']::personalization_type[], ARRAY['work_anniversary_3']::occasion_type[], ARRAY['connector','creator']::employee_archetype[], ARRAY['wearable'], 'standard', false, false, true, 4);

-- ---------- Bucket C — CEO & Leadership Recognition -------------------------
INSERT INTO products (sku, bucket_id, name, slug, tagline, description, who_is_it_for, insight, wow_score, cogs, price_single, price_bulk_25, price_bulk_100, margin_percent, lead_time_days, rush_lead_time_days, moq, materials, personalization_types, occasions, archetypes, tags, recommended_packaging, is_featured, is_bestseller, is_new, sort_order) VALUES
('NV-C01', (SELECT id FROM buckets WHERE code='C'), 'Wax-Sealed CEO Letter Box', 'wax-sealed-ceo-letter-box', 'The note is the product', 'A letter-led recognition package with a premium card and wax seal.', 'Spot awards and leadership moments', 'The CEO note is the true product; the box just frames it.', 8, 370, 1290, 1190, 990, 66, 4, 2, 10, ARRAY['paper','wax'], ARRAY['print']::personalization_type[], ARRAY['spot_award']::occasion_type[], ARRAY['achiever','scholar']::employee_archetype[], ARRAY['ceremony','keepsake'], 'premium', true, false, false, 1),
('NV-C02', (SELECT id FROM buckets WHERE code='C'), 'Marble Achievement Trophy', 'marble-achievement-trophy', 'Real boardroom weight', 'A heavier marble award for quarterly or annual performance.', 'CEO awards, annual stars', 'It feels like a real boardroom object, not event swag.', 9, 1020, 2990, 2790, 2490, 66, 9, 5, 10, ARRAY['marble','brass'], ARRAY['laser_engrave']::personalization_type[], ARRAY['annual_award']::occasion_type[], ARRAY['achiever']::employee_archetype[], ARRAY['award','status'], 'flagship', true, true, false, 2),
('NV-C03', (SELECT id FROM buckets WHERE code='C'), 'Executive Pen Set', 'executive-pen-set', 'Authority without noise', 'A serious desk pen set engraved with the recipient''s name.', 'High performers, directors', 'A pen is a classic because it still sits on a desk years later.', 8, 555, 1490, 1390, 1290, 63, 6, 4, 20, ARRAY['metal'], ARRAY['laser_engrave']::personalization_type[], ARRAY['promotion']::occasion_type[], ARRAY['achiever','minimalist']::employee_archetype[], ARRAY['desk-test','premium'], 'premium', false, false, false, 3),
('NV-C04', (SELECT id FROM buckets WHERE code='C'), 'Boardroom Hamper', 'boardroom-hamper', 'Expensive before it opens', 'A multi-item premium hamper for leadership occasions.', 'Annual leadership recognition', 'Flagship leadership hampers should look expensive before they are opened.', 9, 1590, 4990, 4590, 3990, 68, 9, 5, 5, ARRAY['mixed'], ARRAY['print']::personalization_type[], ARRAY['annual_award']::occasion_type[], ARRAY['achiever','connector']::employee_archetype[], ARRAY['hamper','status'], 'flagship', false, false, true, 4);

-- ---------- Bucket D — Festive & Seasonal -----------------------------------
INSERT INTO products (sku, bucket_id, name, slug, tagline, description, who_is_it_for, insight, wow_score, cogs, price_single, price_bulk_25, price_bulk_100, margin_percent, lead_time_days, rush_lead_time_days, moq, materials, personalization_types, occasions, archetypes, tags, recommended_packaging, is_featured, is_bestseller, is_new, sort_order) VALUES
('NV-D01', (SELECT id FROM buckets WHERE code='D'), 'Personalised Diya Box', 'personalised-diya-box', 'Diwali, done thoughtfully', 'A Diwali-ready diya hamper with name card and festive insert.', 'Diwali employee gifting', 'It is seasonal, local, and culturally obvious.', 8, 300, 790, 690, 590, 62, 5, 3, 25, ARRAY['terracotta'], ARRAY['print']::personalization_type[], ARRAY['festival_diwali']::occasion_type[], ARRAY['root','connector']::employee_archetype[], ARRAY['festive','eco'], 'standard', true, true, false, 1),
('NV-D02', (SELECT id FROM buckets WHERE code='D'), 'Festive Candle Hamper', 'festive-candle-hamper', 'Scent becomes memory', 'Soy candle and décor box that works across festivals.', 'Diwali, Christmas, New Year', 'Scent creates memory faster than almost any other object.', 8, 410, 1190, 1090, 990, 65, 6, 4, 25, ARRAY['soy-wax','paper'], ARRAY['print']::personalization_type[], ARRAY['festival_diwali','festival_christmas']::occasion_type[], ARRAY['creator','minimalist']::employee_archetype[], ARRAY['festive'], 'premium', false, false, false, 2),
('NV-D03', (SELECT id FROM buckets WHERE code='D'), 'Holi Colour Kit', 'holi-colour-kit', 'Safe, premium, photogenic', 'A premium, safe, photogenic Holi celebration pack.', 'Team celebrations and offsites', 'It is easy to distribute and easy to post.', 7, 240, 690, 590, 490, 65, 4, 2, 50, ARRAY['eco-colour'], ARRAY['print']::personalization_type[], ARRAY['festival_holi']::occasion_type[], ARRAY['connector','explorer']::employee_archetype[], ARRAY['festive','instagram-ready'], 'budget', false, false, true, 3),
('NV-D04', (SELECT id FROM buckets WHERE code='D'), 'Seasonal Mixed Hamper', 'seasonal-mixed-hamper', 'Flexible festive flagship', 'A flexible festive hamper with snacks, keepsake, and card.', 'Diwali and year-end', 'Flexibility matters when the client does not know the final count yet.', 8, 640, 1790, 1690, 1490, 64, 7, 4, 20, ARRAY['mixed'], ARRAY['print']::personalization_type[], ARRAY['festival_diwali','new_year']::occasion_type[], ARRAY['connector']::employee_archetype[], ARRAY['festive','hamper'], 'premium', false, false, false, 4);

-- ---------- Bucket E — Client Appreciation ----------------------------------
INSERT INTO products (sku, bucket_id, name, slug, tagline, description, who_is_it_for, insight, wow_score, cogs, price_single, price_bulk_25, price_bulk_100, margin_percent, lead_time_days, rush_lead_time_days, moq, materials, personalization_types, occasions, archetypes, tags, recommended_packaging, is_featured, is_bestseller, is_new, sort_order) VALUES
('NV-E01', (SELECT id FROM buckets WHERE code='E'), 'Client Leather Portfolio', 'client-leather-portfolio', 'Visible in every meeting', 'A premium portfolio for business reviews and meetings, dual-logo and named.', 'Key client onboarding, renewals', 'It is usable in meetings, which keeps your brand visible.', 8, 850, 2490, 2290, 1990, 60, 7, 5, 10, ARRAY['leather'], ARRAY['emboss']::personalization_type[], ARRAY['client_appreciation']::occasion_type[], ARRAY['achiever','minimalist']::employee_archetype[], ARRAY['premium','daily-use'], 'premium', true, false, false, 1),
('NV-E02', (SELECT id FROM buckets WHERE code='E'), 'City Map Art', 'city-map-art', 'Anchor the relationship to a place', 'A destination map showing where the relationship began or matters most.', 'Deal closures, anniversaries', 'The map makes the relationship feel geographically anchored.', 8, 640, 1990, 1790, 1490, 67, 7, 4, 10, ARRAY['print','frame'], ARRAY['print']::personalization_type[], ARRAY['deal_closure']::occasion_type[], ARRAY['explorer','creator']::employee_archetype[], ARRAY['keepsake'], 'premium', false, false, false, 2),
('NV-E03', (SELECT id FROM buckets WHERE code='E'), 'Decanter Presentation Set', 'decanter-presentation-set', 'A close-the-room object', 'A boardroom-grade presentation set without overdoing it.', 'High-value deal closures', 'This is a close-the-room object, not a swag item.', 9, 1310, 3990, 3690, 2990, 67, 9, 5, 5, ARRAY['glass','brass'], ARRAY['laser_engrave']::personalization_type[], ARRAY['deal_closure']::occasion_type[], ARRAY['achiever']::employee_archetype[], ARRAY['premium','status'], 'flagship', true, true, false, 3),
('NV-E04', (SELECT id FROM buckets WHERE code='E'), 'Tea / Coffee Ritual Set', 'tea-coffee-ritual-set', 'Keep the relationship warm', 'An elegant sampler that works in offices and at home.', 'Client relationship nurturing', 'Shared rituals keep the relationship warm without being loud.', 7, 420, 1290, 1190, 990, 67, 5, 3, 25, ARRAY['mixed'], ARRAY['print']::personalization_type[], ARRAY['client_appreciation']::occasion_type[], ARRAY['connector','root']::employee_archetype[], ARRAY['hamper'], 'standard', false, false, true, 4);

-- ---------- Bucket F — Experience Kits --------------------------------------
INSERT INTO products (sku, bucket_id, name, slug, tagline, description, who_is_it_for, insight, wow_score, cogs, price_single, price_bulk_25, price_bulk_100, margin_percent, lead_time_days, rush_lead_time_days, moq, materials, personalization_types, occasions, archetypes, tags, recommended_packaging, is_featured, is_bestseller, is_new, sort_order) VALUES
('NV-F01', (SELECT id FROM buckets WHERE code='F'), 'Onboarding Story Kit', 'onboarding-story-kit', 'The kit people post', 'A flagship Day-1 kit with 5–7 items and a strong narrative arc.', 'Premium onboarding', 'This is the first kit people post because it feels expensive and intentional.', 9, 1830, 4990, 4590, 3990, 63, 9, 5, 20, ARRAY['mixed'], ARRAY['laser_engrave','print','emboss']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['achiever','creator']::employee_archetype[], ARRAY['kit','instagram-ready'], 'flagship', true, true, false, 1),
('NV-F02', (SELECT id FROM buckets WHERE code='F'), 'CEO Recognition Kit', 'ceo-recognition-kit', 'A public signal of status', 'A leadership-grade box that makes recognition feel direct.', 'Top performer, MVP, promotion', 'This is a public signal of internal status.', 10, 2220, 6990, 6490, 4990, 68, 9, 5, 10, ARRAY['mixed'], ARRAY['laser_engrave','print']::personalization_type[], ARRAY['annual_award','promotion']::occasion_type[], ARRAY['achiever']::employee_archetype[], ARRAY['kit','status'], 'flagship', true, false, false, 2),
('NV-F03', (SELECT id FROM buckets WHERE code='F'), 'Diwali Flagship Kit', 'diwali-flagship-kit', 'Festive without disposable', 'A premium festive box with ritual and utility layers.', 'Company-wide festive gifting', 'It works because it is festive without becoming disposable.', 9, 1650, 4990, 4490, 3990, 67, 9, 5, 20, ARRAY['mixed'], ARRAY['print']::personalization_type[], ARRAY['festival_diwali']::occasion_type[], ARRAY['connector','root']::employee_archetype[], ARRAY['kit','festive'], 'flagship', false, false, true, 3),
('NV-F04', (SELECT id FROM buckets WHERE code='F'), 'Offsite Memory Kit', 'offsite-memory-kit', 'Carry the event back home', 'A team event kit that carries the event back home.', 'Offsites, summits, retreats', 'Events are wasted if the memory dies on the same day.', 8, 1250, 2990, 2790, 2490, 58, 7, 4, 20, ARRAY['mixed'], ARRAY['print']::personalization_type[], ARRAY['team_offsite']::occasion_type[], ARRAY['explorer','connector']::employee_archetype[], ARRAY['kit'], 'premium', false, false, false, 4);

-- ---------- Bucket G — Tech-Forward & Digital -------------------------------
INSERT INTO products (sku, bucket_id, name, slug, tagline, description, who_is_it_for, insight, wow_score, cogs, price_single, price_bulk_25, price_bulk_100, margin_percent, lead_time_days, rush_lead_time_days, moq, materials, personalization_types, occasions, archetypes, tags, recommended_packaging, is_featured, is_bestseller, is_new, sort_order) VALUES
('NV-G01', (SELECT id FROM buckets WHERE code='G'), 'QR CEO Video Stand', 'qr-ceo-video-stand', 'A static gift goes live', 'A desk stand that opens a personal CEO video on scan.', 'Onboarding, awards', 'It turns a static gift into a live message.', 9, 370, 990, 890, 790, 63, 5, 3, 25, ARRAY['acrylic','wood'], ARRAY['laser_engrave','uv_print']::personalization_type[], ARRAY['onboarding','spot_award']::occasion_type[], ARRAY['builder','creator']::employee_archetype[], ARRAY['digital','desk-test'], 'standard', true, true, false, 1),
('NV-G02', (SELECT id FROM buckets WHERE code='G'), 'NFC Legacy Card', 'nfc-legacy-card', 'Tap to a memory page', 'A premium card that launches a memory page when tapped.', 'Leadership gifts', 'The object survives because the digital layer refreshes it.', 8, 425, 1290, 1190, 990, 67, 6, 4, 25, ARRAY['metal','pvc'], ARRAY['uv_print']::personalization_type[], ARRAY['promotion']::occasion_type[], ARRAY['builder','minimalist']::employee_archetype[], ARRAY['digital','premium'], 'premium', false, false, true, 2),
('NV-G03', (SELECT id FROM buckets WHERE code='G'), 'AR Packaging', 'ar-packaging', 'The reveal is the story', 'Packaging that reveals a hidden message in augmented reality.', 'Launches, premium campaigns', 'This earns social posts because the reveal is the story.', 9, 670, 1990, 1790, 1490, 66, 7, 5, 10, ARRAY['print'], ARRAY['print']::personalization_type[], ARRAY['client_appreciation']::occasion_type[], ARRAY['creator','explorer']::employee_archetype[], ARRAY['digital','instagram-ready'], 'premium', false, false, false, 3),
('NV-G04', (SELECT id FROM buckets WHERE code='G'), 'Digital Memory Archive Frame', 'digital-memory-archive-frame', 'An evolving memory', 'A print frame that opens a curated archive of moments.', 'Anniversaries', 'It creates an evolving memory instead of a dead object.', 8, 500, 1490, 1390, 1190, 66, 7, 4, 20, ARRAY['frame','print'], ARRAY['print']::personalization_type[], ARRAY['work_anniversary_3']::occasion_type[], ARRAY['scholar','creator']::employee_archetype[], ARRAY['digital','keepsake'], 'premium', false, false, false, 4);

-- ---------- Bucket H — Sustainability & Eco ---------------------------------
INSERT INTO products (sku, bucket_id, name, slug, tagline, description, who_is_it_for, insight, wow_score, cogs, price_single, price_bulk_25, price_bulk_100, margin_percent, lead_time_days, rush_lead_time_days, moq, materials, personalization_types, occasions, archetypes, tags, recommended_packaging, is_featured, is_bestseller, is_new, sort_order) VALUES
('NV-H01', (SELECT id FROM buckets WHERE code='H'), 'Seed Paper Notebook', 'seed-paper-notebook', 'Pages you can plant', 'A notebook whose pages can be planted after use.', 'Eco-conscious onboarding', 'It links utility to an actual sustainability story.', 7, 310, 890, 790, 690, 65, 6, 4, 25, ARRAY['seed-paper'], ARRAY['print']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['root','scholar']::employee_archetype[], ARRAY['eco'], 'standard', true, false, false, 1),
('NV-H02', (SELECT id FROM buckets WHERE code='H'), 'Bamboo Desk Set', 'bamboo-desk-set', 'Eco that stays desirable', 'A functional bamboo desk kit with a modern finish.', 'Green workplace gifts', 'Eco is only credible when the object is still desirable.', 8, 390, 1090, 990, 890, 64, 6, 4, 25, ARRAY['bamboo'], ARRAY['laser_engrave']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['builder','minimalist']::employee_archetype[], ARRAY['eco','desk-test'], 'standard', false, true, false, 2),
('NV-H03', (SELECT id FROM buckets WHERE code='H'), 'Terracotta Planter Kit', 'terracotta-planter-kit', 'A real plant beats plastic', 'A natural planter kit for desks and homes.', 'Sustainability campaigns', 'A real plant beats a plastic keepsake every time.', 8, 355, 990, 890, 790, 64, 6, 4, 25, ARRAY['terracotta','plant'], ARRAY['print']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['root','creator']::employee_archetype[], ARRAY['eco','desk-test'], 'standard', false, false, true, 3),
('NV-H04', (SELECT id FROM buckets WHERE code='H'), 'Organic Cotton Tee', 'organic-cotton-tee', 'If the fabric feels cheap, the claim fails', 'A soft organic cotton tee with restrained branding.', 'Brand and climate-conscious teams', 'If the fabric feels cheap, the sustainability claim fails.', 8, 430, 1090, 990, 890, 61, 7, 5, 25, ARRAY['organic-cotton'], ARRAY['dtf','embroidery']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['connector','creator']::employee_archetype[], ARRAY['eco','wearable'], 'standard', false, false, false, 4);

-- ---------- Festival Calendar (2025–2026) -----------------------------------
INSERT INTO festival_calendar (name, occasion_type, date, year, description, recommended_buckets, is_active) VALUES
('Makar Sankranti / Pongal', 'festival_pongal', '2025-01-14', 2025, 'Harvest festival celebrated across India.', ARRAY['D']::bucket_code[], true),
('Republic Day', 'custom', '2025-01-26', 2025, 'National holiday.', ARRAY['D']::bucket_code[], true),
('Holi', 'festival_holi', '2025-03-14', 2025, 'Festival of colours.', ARRAY['D']::bucket_code[], true),
('Eid al-Fitr', 'festival_eid', '2025-03-31', 2025, 'Approximate date — confirm by moon sighting.', ARRAY['D']::bucket_code[], true),
('Raksha Bandhan', 'custom', '2025-08-09', 2025, 'Celebration of sibling bonds.', ARRAY['D']::bucket_code[], true),
('Independence Day', 'custom', '2025-08-15', 2025, 'National holiday.', ARRAY['D']::bucket_code[], true),
('Ganesh Chaturthi', 'custom', '2025-08-27', 2025, 'Festival honouring Lord Ganesha.', ARRAY['D']::bucket_code[], true),
('Onam', 'festival_onam', '2025-09-05', 2025, 'Kerala harvest festival.', ARRAY['D']::bucket_code[], true),
('Navratri', 'custom', '2025-09-22', 2025, 'Nine nights festival.', ARRAY['D']::bucket_code[], true),
('Diwali', 'festival_diwali', '2025-10-20', 2025, 'Festival of lights — peak corporate gifting season.', ARRAY['D','F']::bucket_code[], true),
('Christmas', 'festival_christmas', '2025-12-25', 2025, 'Christmas celebrations.', ARRAY['D']::bucket_code[], true),
('New Year', 'new_year', '2026-01-01', 2026, 'New Year celebrations.', ARRAY['D','F']::bucket_code[], true),
('Makar Sankranti / Pongal', 'festival_pongal', '2026-01-14', 2026, 'Harvest festival celebrated across India.', ARRAY['D']::bucket_code[], true),
('Republic Day', 'custom', '2026-01-26', 2026, 'National holiday.', ARRAY['D']::bucket_code[], true),
('Holi', 'festival_holi', '2026-03-03', 2026, 'Festival of colours.', ARRAY['D']::bucket_code[], true),
('Eid al-Fitr', 'festival_eid', '2026-03-20', 2026, 'Approximate date — confirm by moon sighting.', ARRAY['D']::bucket_code[], true),
('Independence Day', 'custom', '2026-08-15', 2026, 'National holiday.', ARRAY['D']::bucket_code[], true),
('Onam', 'festival_onam', '2026-08-25', 2026, 'Kerala harvest festival.', ARRAY['D']::bucket_code[], true),
('Diwali', 'festival_diwali', '2026-11-08', 2026, 'Festival of lights — peak corporate gifting season.', ARRAY['D','F']::bucket_code[], true),
('Christmas', 'festival_christmas', '2026-12-25', 2026, 'Christmas celebrations.', ARRAY['D']::bucket_code[], true);

-- =============================================================================
-- End of seed
-- =============================================================================
