/**
 * Order Engine - INTERNAL USE ONLY (server-side).
 *
 * Orders are the operational backbone connecting quotes (Prompt 07) to gift
 * records (Prompt 12). Created by the Neon Visuals team (super_admin) after a
 * quote is accepted; clients see a read-only, price-free view.
 *
 * Order numbers are generated by the `set_order_number` DB trigger
 * (format NV-O-YYYY-XXXX). Pricing is stored as integers in Rupees and is
 * NEVER exposed to clients (the API strips financial fields by role).
 *
 * All business logic lives here - never in Supabase functions.
 *
 * Prompt 2 (item 6): switched from the service-role client to the request-scoped
 * RLS client (`createClient`). All callers are authenticated platform staff
 * (the /ops order screens); RLS `orders_*` / `order_*_write_*` policies scope
 * access and `authorize()` at the route layer is the role gate. Order
 * fulfilment writes to gift_records/employee_preferences rely on the
 * `*_platform_write` policies (migration 020). The request-scoped client is
 * imported DYNAMICALLY (see `userDb`) so this server engine stays import-safe
 * from client components that use its exported constants/types.
 */
import type { SupabaseClient } from "@supabase/supabase-js";
import {
  calculatePricing,
  type PackagingTierId,
  type PersonalisationLevelId,
} from "@/lib/engines/pricing";
import { getProductBySku } from "@/lib/catalog";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type OrderStatus =
  | "draft"
  | "confirmed"
  | "in_production"
  | "quality_check"
  | "packed"
  | "shipped"
  | "delivered"
  | "completed"
  | "cancelled";

export type OrderPaymentStatus =
  | "pending"
  | "advance_received"
  | "partially_paid"
  | "fully_paid"
  | "refunded";

export type RecipientDeliveryStatus =
  | "pending"
  | "in_production"
  | "packed"
  | "shipped"
  | "delivered"
  | "returned";

export interface OrderProductInput {
  sku: string;
  quantity: number;
  personalisationType?: string;
  engravingTextTemplate?: string;
  notes?: string;
}

export interface OrderInput {
  companyId: string;
  quoteId?: string;
  /** Stable occasion key (7a pattern) copied from the source quote. */
  occasionKey?: string | null;
  occasionType?: string;
  occasionLabel?: string;
  products: OrderProductInput[];
  packagingTier: PackagingTierId;
  personalisationLevel: PersonalisationLevelId;
  kitCount: number;
  isRush?: boolean;
  rushDays?: number;
  discountPercent?: number;
  deliveryAddress?: string;
  deliveryCity?: string;
  deliveryPincode?: string;
  expectedDeliveryDate?: string;
  internalNotes?: string;
  clientNotes?: string;
  specialInstructions?: string;
  assignedTo?: string;
}

export interface RecipientInput {
  employeeId?: string;
  recipientName: string;
  recipientEmail?: string;
  recipientDepartment?: string;
  personalisationName: string;
  personalisationMessage?: string;
  notes?: string;
}

export interface OrderItem {
  id: string;
  order_id: string;
  product_sku: string;
  product_name: string;
  collection_code: string | null;
  quantity: number;
  /** INTERNAL ONLY. */
  unit_price: number | null;
  /** INTERNAL ONLY. */
  line_total: number | null;
  personalisation_type: string | null;
  engraving_text_template: string | null;
  notes: string | null;
  sort_order: number;
}

export interface OrderRecipient {
  id: string;
  order_id: string;
  employee_id: string | null;
  recipient_name: string;
  recipient_email: string | null;
  recipient_department: string | null;
  personalisation_name: string;
  personalisation_message: string | null;
  delivery_status: RecipientDeliveryStatus;
  delivered_date: string | null;
  tracking_number: string | null;
  gift_record_id: string | null;
  notes: string | null;
}

export interface StatusEntry {
  id: string;
  order_id: string;
  from_status: string | null;
  to_status: string;
  changed_by: string | null;
  notes: string | null;
  created_at: string;
}

export interface Order {
  id: string;
  order_number: string | null;
  company_id: string;
  company_name?: string | null;
  quote_id: string | null;
  status: OrderStatus;
  /** Stable occasion key (7a pattern) carried from the source quote; null for ad-hoc orders. */
  occasion_key: string | null;
  occasion_type: string | null;
  occasion_label: string | null;
  kit_count: number;
  packaging_tier: string;
  personalisation_level: string;
  /** INTERNAL ONLY (financial fields). */
  subtotal: number | null;
  packaging_total: number | null;
  personalisation_total: number | null;
  rush_surcharge: number | null;
  discount_percent: number | null;
  discount_amount: number | null;
  grand_total: number | null;
  per_kit_investment: number | null;
  delivery_address: string | null;
  delivery_city: string | null;
  delivery_pincode: string | null;
  expected_delivery_date: string | null;
  actual_delivery_date: string | null;
  tracking_number: string | null;
  courier_partner: string | null;
  /** INTERNAL ONLY (payment fields). */
  payment_status: OrderPaymentStatus;
  advance_amount: number | null;
  advance_date: string | null;
  balance_amount: number | null;
  balance_date: string | null;
  is_rush: boolean;
  rush_days: number | null;
  /** INTERNAL ONLY. */
  internal_notes: string | null;
  client_notes: string | null;
  special_instructions: string | null;
  created_by: string | null;
  /** INTERNAL ONLY. */
  assigned_to: string | null;
  created_at: string;
  updated_at: string;
  items: OrderItem[];
  recipients: OrderRecipient[];
  statusHistory: StatusEntry[];
}

// ---------------------------------------------------------------------------
// Status machine
// ---------------------------------------------------------------------------

// Pure lifecycle constants live in ./order-constants (client-safe). Imported
// for internal use here and re-exported for server callers.
import {
  ORDER_TRANSITIONS,
  canTransition,
  ORDER_STATUS_FLOW,
} from "./order-constants";
export { ORDER_TRANSITIONS, canTransition, ORDER_STATUS_FLOW };

// ---------------------------------------------------------------------------
// Row mapping
// ---------------------------------------------------------------------------

/* eslint-disable @typescript-eslint/no-explicit-any */
function mapItem(row: any): OrderItem {
  return {
    id: row.id,
    order_id: row.order_id,
    product_sku: row.product_sku,
    product_name: row.product_name,
    collection_code: row.collection_code ?? null,
    quantity: Number(row.quantity ?? 1),
    unit_price: row.unit_price ?? null,
    line_total: row.line_total ?? null,
    personalisation_type: row.personalisation_type ?? null,
    engraving_text_template: row.engraving_text_template ?? null,
    notes: row.notes ?? null,
    sort_order: Number(row.sort_order ?? 0),
  };
}

function mapRecipient(row: any): OrderRecipient {
  return {
    id: row.id,
    order_id: row.order_id,
    employee_id: row.employee_id ?? null,
    recipient_name: row.recipient_name,
    recipient_email: row.recipient_email ?? null,
    recipient_department: row.recipient_department ?? null,
    personalisation_name: row.personalisation_name,
    personalisation_message: row.personalisation_message ?? null,
    delivery_status: (row.delivery_status ?? "pending") as RecipientDeliveryStatus,
    delivered_date: row.delivered_date ?? null,
    tracking_number: row.tracking_number ?? null,
    gift_record_id: row.gift_record_id ?? null,
    notes: row.notes ?? null,
  };
}

function mapStatusEntry(row: any): StatusEntry {
  return {
    id: row.id,
    order_id: row.order_id,
    from_status: row.from_status ?? null,
    to_status: row.to_status,
    changed_by: row.changed_by ?? null,
    notes: row.notes ?? null,
    created_at: row.created_at,
  };
}

function mapOrder(row: any): Order {
  return {
    id: row.id,
    order_number: row.order_number ?? null,
    company_id: row.company_id,
    company_name: row.companies?.name ?? row.company_name ?? null,
    quote_id: row.quote_id ?? null,
    status: row.status as OrderStatus,
    occasion_key: row.occasion_key ?? null,
    occasion_type: row.occasion_type ?? null,
    occasion_label: row.occasion_label ?? null,
    kit_count: Number(row.kit_count ?? 1),
    packaging_tier: row.packaging_tier ?? "standard",
    personalisation_level: row.personalisation_level ?? "name_occasion",
    subtotal: row.subtotal ?? null,
    packaging_total: row.packaging_total ?? null,
    personalisation_total: row.personalisation_total ?? null,
    rush_surcharge: row.rush_surcharge ?? null,
    discount_percent: row.discount_percent ?? null,
    discount_amount: row.discount_amount ?? null,
    grand_total: row.grand_total ?? null,
    per_kit_investment: row.per_kit_investment ?? null,
    delivery_address: row.delivery_address ?? null,
    delivery_city: row.delivery_city ?? null,
    delivery_pincode: row.delivery_pincode ?? null,
    expected_delivery_date: row.expected_delivery_date ?? null,
    actual_delivery_date: row.actual_delivery_date ?? null,
    tracking_number: row.tracking_number ?? null,
    courier_partner: row.courier_partner ?? null,
    payment_status: (row.payment_status ?? "pending") as OrderPaymentStatus,
    advance_amount: row.advance_amount ?? null,
    advance_date: row.advance_date ?? null,
    balance_amount: row.balance_amount ?? null,
    balance_date: row.balance_date ?? null,
    is_rush: Boolean(row.is_rush),
    rush_days: row.rush_days ?? null,
    internal_notes: row.internal_notes ?? null,
    client_notes: row.client_notes ?? null,
    special_instructions: row.special_instructions ?? null,
    created_by: row.created_by ?? null,
    assigned_to: row.assigned_to ?? null,
    created_at: row.created_at,
    updated_at: row.updated_at,
    items: (row.order_items ?? []).map(mapItem).sort(
      (a: OrderItem, b: OrderItem) => a.sort_order - b.sort_order,
    ),
    recipients: (row.order_recipients ?? []).map(mapRecipient),
    statusHistory: (row.order_status_history ?? [])
      .map(mapStatusEntry)
      .sort((a: StatusEntry, b: StatusEntry) =>
        a.created_at.localeCompare(b.created_at),
      ),
  };
}
/* eslint-enable @typescript-eslint/no-explicit-any */

const ORDER_SELECT =
  "*, companies(name), order_items(*), order_recipients(*), order_status_history(*)";

// ---------------------------------------------------------------------------
// Create / update
// ---------------------------------------------------------------------------

export async function createOrder(
  input: OrderInput,
  createdBy?: string,
): Promise<Order> {
  const supa = await userDb();

  const pricing = await calculatePricing({
    products: input.products.map((p) => ({ sku: p.sku, quantity: p.quantity })),
    kitCount: input.kitCount,
    packagingTier: input.packagingTier,
    rushOrder: input.isRush ?? false,
    rushDays: input.rushDays,
    personalisation: input.personalisationLevel,
    resumeIntelligence: false,
  });

  const discountPercent = input.discountPercent ?? 0;
  const discountAmount = Math.round((pricing.grandTotal * discountPercent) / 100);
  const grandTotal = pricing.grandTotal - discountAmount;
  const perKit = Math.round(grandTotal / Math.max(1, input.kitCount));

  const { data: orderRow, error: orderErr } = await supa
    .from("orders")
    .insert({
      company_id: input.companyId,
      quote_id: input.quoteId ?? null,
      status: "draft",
      occasion_key: input.occasionKey ?? null,
      occasion_type: input.occasionType ?? null,
      occasion_label: input.occasionLabel ?? null,
      kit_count: input.kitCount,
      packaging_tier: input.packagingTier,
      personalisation_level: input.personalisationLevel,
      subtotal: pricing.subtotal,
      packaging_total: pricing.packagingTotal,
      personalisation_total: pricing.personalisationTotal,
      rush_surcharge: pricing.rushSurchargeAmount,
      discount_percent: discountPercent,
      discount_amount: discountAmount,
      grand_total: grandTotal,
      per_kit_investment: perKit,
      delivery_address: input.deliveryAddress ?? null,
      delivery_city: input.deliveryCity ?? null,
      delivery_pincode: input.deliveryPincode ?? null,
      expected_delivery_date: input.expectedDeliveryDate ?? null,
      is_rush: input.isRush ?? false,
      rush_days: input.rushDays ?? null,
      internal_notes: input.internalNotes ?? null,
      client_notes: input.clientNotes ?? null,
      special_instructions: input.specialInstructions ?? null,
      created_by: createdBy ?? null,
      assigned_to: input.assignedTo ?? null,
    })
    .select("id")
    .single();
  if (orderErr) throw new Error(`Create order failed: ${orderErr.message}`);

  const orderId = orderRow.id as string;

  // Line items (price snapshot from the pricing engine).
  const priceBySku = new Map(pricing.lineItems.map((li) => [li.sku, li]));
  const itemRows = input.products.map((p, idx) => {
    const li = priceBySku.get(p.sku);
    const product = getProductBySku(p.sku);
    return {
      order_id: orderId,
      product_sku: p.sku,
      product_name: li?.productName ?? product?.name ?? p.sku,
      collection_code: product?.bucket ?? null,
      quantity: p.quantity,
      unit_price: li?.unitPrice ?? null,
      line_total: li?.lineTotal ?? null,
      personalisation_type: p.personalisationType ?? null,
      engraving_text_template: p.engravingTextTemplate ?? null,
      notes: p.notes ?? null,
      sort_order: idx,
    };
  });
  if (itemRows.length > 0) {
    const { error } = await supa.from("order_items").insert(itemRows);
    if (error) throw new Error(`Create order items failed: ${error.message}`);
  }

  // Initial status history entry.
  await supa.from("order_status_history").insert({
    order_id: orderId,
    from_status: null,
    to_status: "draft",
    changed_by: createdBy ?? null,
    notes: "Order created",
  });

  const order = await getOrder(orderId);
  if (!order) throw new Error("Create order failed: could not reload order");
  return order;
}

const UPDATABLE_COLUMNS: Record<string, string> = {
  occasionType: "occasion_type",
  occasionLabel: "occasion_label",
  expectedDeliveryDate: "expected_delivery_date",
  actualDeliveryDate: "actual_delivery_date",
  deliveryAddress: "delivery_address",
  deliveryCity: "delivery_city",
  deliveryPincode: "delivery_pincode",
  trackingNumber: "tracking_number",
  courierPartner: "courier_partner",
  internalNotes: "internal_notes",
  clientNotes: "client_notes",
  specialInstructions: "special_instructions",
  assignedTo: "assigned_to",
  paymentStatus: "payment_status",
  advanceAmount: "advance_amount",
  advanceDate: "advance_date",
  balanceAmount: "balance_amount",
  balanceDate: "balance_date",
};

export interface OrderUpdate {
  occasionType?: string | null;
  occasionLabel?: string | null;
  expectedDeliveryDate?: string | null;
  actualDeliveryDate?: string | null;
  deliveryAddress?: string | null;
  deliveryCity?: string | null;
  deliveryPincode?: string | null;
  trackingNumber?: string | null;
  courierPartner?: string | null;
  internalNotes?: string | null;
  clientNotes?: string | null;
  specialInstructions?: string | null;
  assignedTo?: string | null;
  paymentStatus?: OrderPaymentStatus;
  advanceAmount?: number | null;
  advanceDate?: string | null;
  balanceAmount?: number | null;
  balanceDate?: string | null;
}

export async function updateOrder(
  id: string,
  updates: OrderUpdate,
): Promise<Order> {
  const supa = await userDb();
  const payload: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(updates)) {
    const col = UPDATABLE_COLUMNS[key];
    if (col && value !== undefined) payload[col] = value;
  }
  if (Object.keys(payload).length > 0) {
    const { error } = await supa.from("orders").update(payload).eq("id", id);
    if (error) throw new Error(`Update order failed: ${error.message}`);
  }
  const order = await getOrder(id);
  if (!order) throw new Error("Order not found");
  return order;
}

// ---------------------------------------------------------------------------
// Read
// ---------------------------------------------------------------------------

export async function getOrder(id: string): Promise<Order | null> {
  const supa = await userDb();
  const { data, error } = await supa
    .from("orders")
    .select(ORDER_SELECT)
    .eq("id", id)
    .maybeSingle();
  if (error) throw new Error(`Get order failed: ${error.message}`);
  return data ? mapOrder(data) : null;
}

export interface ListOrdersOptions {
  companyId?: string;
  status?: OrderStatus;
  dateRange?: { start: string; end: string };
  search?: string;
  page?: number;
  pageSize?: number;
}

export async function listOrders(
  options: ListOrdersOptions = {},
): Promise<{ orders: Order[]; total: number }> {
  const { page = 1, pageSize = 25 } = options;
  const supa = await userDb();
  let query = supa
    .from("orders")
    .select(ORDER_SELECT, { count: "exact" })
    .order("created_at", { ascending: false });

  if (options.companyId) query = query.eq("company_id", options.companyId);
  if (options.status) query = query.eq("status", options.status);
  if (options.search) {
    query = query.or(
      `order_number.ilike.%${options.search}%,occasion_label.ilike.%${options.search}%`,
    );
  }
  if (options.dateRange) {
    query = query
      .gte("created_at", options.dateRange.start)
      .lte("created_at", options.dateRange.end);
  }

  const from = (page - 1) * pageSize;
  query = query.range(from, from + pageSize - 1);

  const { data, count, error } = await query;
  if (error) throw new Error(`List orders failed: ${error.message}`);
  return { orders: (data ?? []).map(mapOrder), total: count ?? 0 };
}

export async function getOrderStatusHistory(
  orderId: string,
): Promise<StatusEntry[]> {
  const supa = await userDb();
  const { data, error } = await supa
    .from("order_status_history")
    .select("*")
    .eq("order_id", orderId)
    .order("created_at", { ascending: true });
  if (error) throw new Error(`Get status history failed: ${error.message}`);
  return (data ?? []).map(mapStatusEntry);
}

// ---------------------------------------------------------------------------
// Status management
// ---------------------------------------------------------------------------

export async function updateOrderStatus(
  id: string,
  newStatus: OrderStatus,
  notes?: string,
  changedBy?: string,
): Promise<void> {
  const supa = await userDb();
  const { data: current, error: readErr } = await supa
    .from("orders")
    .select("status")
    .eq("id", id)
    .maybeSingle();
  if (readErr) throw new Error(`Update status failed: ${readErr.message}`);
  if (!current) throw new Error("Order not found");

  const from = current.status as OrderStatus;
  if (!canTransition(from, newStatus)) {
    throw new Error(`Invalid status transition: ${from} → ${newStatus}`);
  }
  if (newStatus === "cancelled" && !notes?.trim()) {
    throw new Error("A reason is required to cancel an order.");
  }

  const patch: Record<string, unknown> = { status: newStatus };
  if (newStatus === "delivered") {
    patch.actual_delivery_date = new Date().toISOString().slice(0, 10);
  }

  const { error: updErr } = await supa.from("orders").update(patch).eq("id", id);
  if (updErr) throw new Error(`Update status failed: ${updErr.message}`);

  await supa.from("order_status_history").insert({
    order_id: id,
    from_status: from,
    to_status: newStatus,
    changed_by: changedBy ?? null,
    notes: notes ?? null,
  });

  // On delivery, generate gift records for the memory engine.
  if (newStatus === "delivered") {
    await generateGiftRecords(id);
  }

  // §7 transition notifications via the 6a engine (Prompt 7c-i). Non-fatal, service-role, deduped.
  // in_production → hr (in-app); shipped → hr + dept managers (email + tracking); delivered → hr.
  if (newStatus === "in_production" || newStatus === "shipped" || newStatus === "delivered") {
    try {
      const { createAdminClient } = await import("@/lib/supabase/admin");
      const { notifyOrderStatusChange } = await import("@/lib/engines/notifications");
      const admin = createAdminClient();
      const { data: ord } = await admin
        .from("orders")
        .select("company_id, order_number, tracking_number, courier_partner")
        .eq("id", id)
        .maybeSingle();
      if (ord?.company_id) {
        await notifyOrderStatusChange(admin, {
          orderId: id,
          companyId: ord.company_id as string,
          orderNumber: (ord.order_number as string | null) ?? null,
          status: newStatus,
          trackingNumber: (ord.tracking_number as string | null) ?? null,
          courierPartner: (ord.courier_partner as string | null) ?? null,
        });
      }
    } catch (e) {
      console.error("[order.updateOrderStatus] §7 transition notify failed:", e);
    }
  }
}

/**
 * Loads the data needed to send a status-change email (company contact +
 * order details). Used by the status API route - kept out of the engine's
 * status mutation so this module stays client-bundle-safe.
 */
export interface OrderEmailContext {
  to: string;
  clientName: string;
  orderNumber: string;
  occasion: string;
  kitCount: number;
  products: Array<{ name: string; sku: string }>;
  expectedDelivery?: string;
  trackingNumber?: string;
  courierPartner?: string;
}

export async function getOrderEmailContext(
  orderId: string,
): Promise<OrderEmailContext | null> {
  const order = await getOrder(orderId);
  if (!order) return null;
  const supa = await userDb();
  const { data: company } = await supa
    .from("companies")
    .select("name, primary_contact_name, primary_contact_email")
    .eq("id", order.company_id)
    .maybeSingle();
  const to = (company?.primary_contact_email as string | null) ?? null;
  if (!to) return null;
  return {
    to,
    clientName:
      (company?.primary_contact_name as string | null) ?? order.company_name ?? "there",
    orderNumber: order.order_number ?? "",
    occasion: order.occasion_label ?? order.occasion_type ?? "Gifting",
    kitCount: order.kit_count,
    products: order.items.map((i) => ({ name: i.product_name, sku: i.product_sku })),
    expectedDelivery: order.expected_delivery_date ?? undefined,
    trackingNumber: order.tracking_number ?? undefined,
    courierPartner: order.courier_partner ?? undefined,
  };
}

// ---------------------------------------------------------------------------
// Recipient management
// ---------------------------------------------------------------------------

export async function addRecipients(
  orderId: string,
  recipients: RecipientInput[],
): Promise<void> {
  if (recipients.length === 0) return;
  const supa = await userDb();
  const rows = recipients.map((r) => ({
    order_id: orderId,
    employee_id: r.employeeId ?? null,
    recipient_name: r.recipientName,
    recipient_email: r.recipientEmail ?? null,
    recipient_department: r.recipientDepartment ?? null,
    personalisation_name: r.personalisationName,
    personalisation_message: r.personalisationMessage ?? null,
    notes: r.notes ?? null,
    delivery_status: "pending" as const,
  }));
  const { error } = await supa.from("order_recipients").insert(rows);
  if (error) throw new Error(`Add recipients failed: ${error.message}`);
}

export async function updateRecipientStatus(
  recipientId: string,
  status: RecipientDeliveryStatus,
): Promise<void> {
  const supa = await userDb();
  const patch: Record<string, unknown> = { delivery_status: status };
  if (status === "delivered") {
    patch.delivered_date = new Date().toISOString().slice(0, 10);
  }
  const { error } = await supa
    .from("order_recipients")
    .update(patch)
    .eq("id", recipientId);
  if (error) throw new Error(`Update recipient failed: ${error.message}`);
}

export async function removeRecipient(recipientId: string): Promise<void> {
  const supa = await userDb();
  const { error } = await supa
    .from("order_recipients")
    .delete()
    .eq("id", recipientId);
  if (error) throw new Error(`Remove recipient failed: ${error.message}`);
}

export async function getOrderRecipients(
  orderId: string,
): Promise<OrderRecipient[]> {
  const supa = await userDb();
  const { data, error } = await supa
    .from("order_recipients")
    .select("*")
    .eq("order_id", orderId)
    .order("recipient_name", { ascending: true });
  if (error) throw new Error(`Get recipients failed: ${error.message}`);
  return (data ?? []).map(mapRecipient);
}

// ---------------------------------------------------------------------------
// Quote → Order conversion
// ---------------------------------------------------------------------------

/**
 * Converts an accepted quote into a draft order. Quotes are not linked to a
 * company directly (they store a free-text client company), so the company is
 * resolved by name match, or supplied explicitly via `companyId`.
 */
export async function convertQuoteToOrder(
  quoteId: string,
  companyId?: string,
  createdBy?: string,
): Promise<Order> {
  const supa = await userDb();
  const { data: quote, error } = await supa
    .from("quotes")
    .select("*")
    .eq("id", quoteId)
    .maybeSingle();
  if (error) throw new Error(`Convert quote failed: ${error.message}`);
  if (!quote) throw new Error("Quote not found");

  // Resolve the company.
  let resolvedCompanyId = companyId ?? null;
  if (!resolvedCompanyId && quote.client_company) {
    const { data: match } = await supa
      .from("companies")
      .select("id")
      .ilike("name", quote.client_company as string)
      .maybeSingle();
    resolvedCompanyId = (match?.id as string) ?? null;
  }
  if (!resolvedCompanyId) {
    throw new Error(
      "Could not resolve a company for this quote. Pass companyId explicitly.",
    );
  }

  const products: OrderProductInput[] = (
    (quote.products as Array<{ sku: string; quantity: number }> | null) ?? []
  ).map((p) => ({ sku: p.sku, quantity: p.quantity }));

  const order = await createOrder(
    {
      companyId: resolvedCompanyId,
      quoteId: quote.id as string,
      occasionKey: (quote.occasion_key as string | null) ?? null,
      occasionLabel: (quote.occasion as string) ?? undefined,
      occasionType: (quote.occasion as string) ?? undefined,
      products,
      packagingTier: (quote.packaging_tier as PackagingTierId) ?? "standard",
      personalisationLevel:
        (quote.personalisation_level as PersonalisationLevelId) ??
        "name_occasion",
      kitCount: Number(quote.kit_count ?? quote.quantity ?? 1),
      isRush: Boolean(quote.rush_order),
      rushDays: (quote.rush_days as number | null) ?? undefined,
      discountPercent: Number(quote.discount_percent ?? 0),
      specialInstructions: (quote.special_instructions as string) ?? undefined,
    },
    createdBy,
  );

  // Mark the quote accepted/converted.
  await supa
    .from("quotes")
    .update({ status: "accepted", accepted_at: new Date().toISOString() })
    .eq("id", quoteId);

  // Prompt 7a: a converted quote = a committed gift. Persist occasion_gift_state (status ordered
  // + order_id) so the cancel-reversal never clears it. Only relevant for occasion-linked quotes.
  if (quote.occasion_key) {
    try {
      const { createAdminClient } = await import("@/lib/supabase/admin");
      const { markGiftOrderedForQuote } = await import("@/lib/engines/notifications");
      await markGiftOrderedForQuote(createAdminClient(), quoteId, order.id);
    } catch (e) {
      console.error("[convertQuoteToOrder] gift-state persist failed:", e);
    }
  }

  return order;
}

// ---------------------------------------------------------------------------
// Gift record generation (on delivery)
// ---------------------------------------------------------------------------

/**
 * For each recipient with a linked employee, create one gift_record per line
 * item, link it back to the order, and bump employee_preferences counters.
 * Idempotent at the recipient level - recipients already linked to a gift
 * record are skipped.
 */
export async function generateGiftRecords(
  orderId: string,
): Promise<{ created: number; errors: string[] }> {
  const supa = await userDb();
  const errors: string[] = [];

  const order = await getOrder(orderId);
  if (!order) return { created: 0, errors: ["Order not found"] };

  const giftedDate =
    order.actual_delivery_date ?? new Date().toISOString().slice(0, 10);
  let created = 0;

  for (const recipient of order.recipients) {
    if (!recipient.employee_id) continue; // snapshot-only recipient
    if (recipient.gift_record_id) continue; // already generated

    let lastGiftId: string | null = null;
    for (const item of order.items) {
      const { data, error } = await supa
        .from("gift_records")
        .insert({
          company_id: order.company_id,
          employee_id: recipient.employee_id,
          product_sku: item.product_sku,
          product_name: item.product_name,
          collection_code: item.collection_code,
          occasion_type: order.occasion_type ?? "custom",
          occasion_label: order.occasion_label,
          // Stable occasion key (7a pattern) so history answers "what did we give Priya AND for
          // which occasion" and joins order↔quote↔occasion by a regen-stable string.
          occasion_key: order.occasion_key,
          gifted_date: giftedDate,
          packaging_tier: order.packaging_tier,
          personalisation_level: order.personalisation_level,
          narrative_message: recipient.personalisation_message,
          engraving_text: recipient.personalisation_name,
          delivery_status: "delivered",
          delivered_date: giftedDate,
          delivery_address: order.delivery_address,
          tracking_number: recipient.tracking_number ?? order.tracking_number,
          unit_price: item.unit_price,
          order_id: order.id,
          quote_id: order.quote_id,
          created_by: order.created_by,
        })
        .select("id")
        .single();
      if (error) {
        errors.push(
          `Recipient ${recipient.recipient_name} / ${item.product_sku}: ${error.message}`,
        );
        continue;
      }
      created += 1;
      lastGiftId = data.id as string;

      // Bump the learned preference counters for this employee.
      await bumpPreferences(supa, order.company_id, recipient.employee_id, giftedDate);
    }

    // Mark the recipient delivered + link to a gift record.
    if (lastGiftId) {
      await supa
        .from("order_recipients")
        .update({
          delivery_status: "delivered",
          delivered_date: giftedDate,
          gift_record_id: lastGiftId,
        })
        .eq("id", recipient.id);
    }
  }

  return { created, errors };
}

/** Ensures an employee_preferences row exists and increments gift counters. */
async function bumpPreferences(
  supa: SupabaseClient,
  companyId: string,
  employeeId: string,
  giftedDate: string,
): Promise<void> {
  const { data: existing } = await supa
    .from("employee_preferences")
    .select("id, total_gifts_received")
    .eq("employee_id", employeeId)
    .maybeSingle();

  if (existing) {
    await supa
      .from("employee_preferences")
      .update({
        total_gifts_received: Number(existing.total_gifts_received ?? 0) + 1,
        last_gifted_date: giftedDate,
      })
      .eq("id", existing.id);
  } else {
    await supa.from("employee_preferences").insert({
      employee_id: employeeId,
      company_id: companyId,
      total_gifts_received: 1,
      last_gifted_date: giftedDate,
    });
  }
}

// ---------------------------------------------------------------------------
// Company employees (for recipient selection in the admin UI)
// ---------------------------------------------------------------------------

export interface OrderEmployeeOption {
  id: string;
  name: string;
  email: string | null;
  department: string | null;
}

export async function listCompanyEmployees(
  companyId: string,
): Promise<OrderEmployeeOption[]> {
  const supa = await userDb();
  const { data, error } = await supa
    .from("employees")
    .select("id, full_name, email, department")
    .eq("company_id", companyId)
    .eq("is_active", true)
    .order("full_name", { ascending: true });
  if (error) throw new Error(`List employees failed: ${error.message}`);
  return (data ?? []).map((e) => ({
    id: e.id as string,
    name: (e.full_name as string) ?? "Employee",
    email: (e.email as string) ?? null,
    department: (e.department as string) ?? null,
  }));
}

export interface CompanyOption {
  id: string;
  name: string;
}

export async function listCompaniesForOrders(): Promise<CompanyOption[]> {
  const supa = await userDb();
  const { data, error } = await supa
    .from("companies")
    .select("id, name")
    .order("name", { ascending: true });
  if (error) throw new Error(`List companies failed: ${error.message}`);
  return (data ?? []).map((c) => ({ id: c.id as string, name: c.name as string }));
}

// ---------------------------------------------------------------------------
// Stats
// ---------------------------------------------------------------------------

export interface OrderStats {
  total: number;
  byStatus: Record<string, number>;
  totalRevenue: number;
  avgOrderValue: number;
  thisMonth: number;
  lastMonth: number;
}

export async function getOrderStats(companyId?: string): Promise<OrderStats> {
  const supa = await userDb();
  let query = supa
    .from("orders")
    .select("status, grand_total, created_at");
  if (companyId) query = query.eq("company_id", companyId);
  const { data, error } = await query;
  if (error) throw new Error(`Order stats failed: ${error.message}`);

  const rows = data ?? [];
  const byStatus: Record<string, number> = {};
  let totalRevenue = 0;
  let revenueCount = 0;
  let thisMonth = 0;
  let lastMonth = 0;

  const now = new Date();
  const thisMonthKey = `${now.getFullYear()}-${now.getMonth()}`;
  const lastDate = new Date(now.getFullYear(), now.getMonth() - 1, 1);
  const lastMonthKey = `${lastDate.getFullYear()}-${lastDate.getMonth()}`;

  for (const r of rows) {
    const status = (r.status as string) ?? "draft";
    byStatus[status] = (byStatus[status] ?? 0) + 1;
    if (status !== "cancelled" && r.grand_total != null) {
      totalRevenue += Number(r.grand_total);
      revenueCount += 1;
    }
    const created = new Date(r.created_at as string);
    const key = `${created.getFullYear()}-${created.getMonth()}`;
    if (key === thisMonthKey) thisMonth += 1;
    if (key === lastMonthKey) lastMonth += 1;
  }

  return {
    total: rows.length,
    byStatus,
    totalRevenue,
    avgOrderValue: revenueCount > 0 ? Math.round(totalRevenue / revenueCount) : 0,
    thisMonth,
    lastMonth,
  };
}

// ---------------------------------------------------------------------------
// Client-facing projection (strips ALL financial + internal fields)
// ---------------------------------------------------------------------------

export interface ClientOrderItem {
  product_sku: string;
  product_name: string;
  collection_code: string | null;
  quantity: number;
}

export interface ClientOrderRecipient {
  recipient_name: string;
  recipient_department: string | null;
  personalisation_name: string;
  delivery_status: RecipientDeliveryStatus;
  delivered_date: string | null;
}

export interface ClientOrder {
  id: string;
  order_number: string | null;
  status: OrderStatus;
  occasion_type: string | null;
  occasion_label: string | null;
  kit_count: number;
  packaging_tier: string;
  expected_delivery_date: string | null;
  actual_delivery_date: string | null;
  tracking_number: string | null;
  courier_partner: string | null;
  client_notes: string | null;
  created_at: string;
  items: ClientOrderItem[];
  recipients: ClientOrderRecipient[];
  statusHistory: Array<{ to_status: string; created_at: string; notes: string | null }>;
}

/** Projects a full Order into the price-free shape sent to clients. */
export function toClientOrder(order: Order): ClientOrder {
  return {
    id: order.id,
    order_number: order.order_number,
    status: order.status,
    occasion_type: order.occasion_type,
    occasion_label: order.occasion_label,
    kit_count: order.kit_count,
    packaging_tier: order.packaging_tier,
    expected_delivery_date: order.expected_delivery_date,
    actual_delivery_date: order.actual_delivery_date,
    tracking_number: order.tracking_number,
    courier_partner: order.courier_partner,
    client_notes: order.client_notes,
    created_at: order.created_at,
    items: order.items.map((i) => ({
      product_sku: i.product_sku,
      product_name: i.product_name,
      collection_code: i.collection_code,
      quantity: i.quantity,
    })),
    recipients: order.recipients.map((r) => ({
      recipient_name: r.recipient_name,
      recipient_department: r.recipient_department,
      personalisation_name: r.personalisation_name,
      delivery_status: r.delivery_status,
      delivered_date: r.delivered_date,
    })),
    statusHistory: order.statusHistory.map((s) => ({
      to_status: s.to_status,
      created_at: s.created_at,
      notes: s.notes,
    })),
  };
}

// Request-scoped RLS client, imported dynamically so this server-only engine
// can be imported by client components (for its exported constants/types)
// without pulling `next/headers` into the client bundle.
async function userDb() {
  const { createClient } = await import("@/lib/supabase/server");
  return createClient();
}
