/**
 * Quote Engine - INTERNAL USE ONLY (server-side).
 * Orchestrates pricing + persistence. Quote numbers are generated by the
 * `set_quote_number` DB trigger (format NV-Q-YYYY-NNNN).
 *
 * Prompt 2 (item 6): switched from the service-role client to the request-scoped
 * RLS client (`createClient`). All callers are authenticated (platform staff via
 * the /ops quote screens); RLS `quotes_read` + `quotes_write_*` policies scope
 * access, and `authorize()` at the route layer is the role gate. The
 * request-scoped client is imported DYNAMICALLY (see `userDb`) so this server
 * engine stays import-safe from client components that use its exported types.
 */
import {
  calculatePricing,
  ALLOWED_LINE_GST_RATES,
  type PackagingTierId,
  type PersonalisationLevelId,
  type PricingResult,
  type PricingProductInput,
  type QuoteLineSource,
} from "@/lib/engines/pricing";

export type QuoteStatus =
  | "draft"
  | "sent"
  | "viewed"
  | "accepted"
  | "rejected"
  | "expired"
  | "converted"
  | "cancelled";

export interface QuoteInput {
  clientName: string;
  clientCompany: string;
  clientEmail: string;
  clientPhone: string;
  occasion: string;
  /** Catalogue, custom, and charge lines (see PricingProductInput). Back-compat: a bare
   *  { sku, quantity } is a catalogue line. */
  products: PricingProductInput[];
  packagingTier: PackagingTierId;
  personalisation: PersonalisationLevelId;
  resumeIntelligence: boolean;
  rushOrder: boolean;
  rushDays?: number;
  timeline?: string;
  sampleMessage?: string;
  specialInstructions?: string;
  kitCount: number;
  validityDays?: number;
  notes?: string;
  discountPercent?: number;
  discountReason?: string;
}

/** Units of quantity permitted on a line (GST UQC codes we support). */
export const ALLOWED_UQC = ["PCS", "BOX", "SET", "KGS", "NOS", "PKT", "DOZ"] as const;
export type Uqc = (typeof ALLOWED_UQC)[number];

/**
 * A product line as stored on a quote (JSONB `quotes.products`). Extended ADDITIVELY in Phase 5A:
 * every new field is optional, so all pre-5A rows (which have only sku/quantity/unitPrice/lineTotal)
 * still parse — a line with no `source` is a catalogue line.
 */
export interface QuoteProductLine {
  sku: string;
  /** Absent = catalogue (back-compat). */
  source?: QuoteLineSource;
  /** REQUIRED for custom/charge lines; derived from the catalogue otherwise. */
  name?: string;
  unitPrice: number;
  quantity: number;
  lineTotal: number;
  /** 4–8 digit HSN/SAC when supplied. */
  hsn?: string;
  /** One of ALLOWED_LINE_GST_RATES when supplied. */
  gstRate?: number;
  /** One of ALLOWED_UQC when supplied. */
  uqc?: string;
  notes?: string;
}

/** Typed validation failure for a stored/inbound quote line. */
export class QuoteValidationError extends Error {
  readonly code: string;
  constructor(code: string, message: string) {
    super(message);
    this.name = "QuoteValidationError";
    this.code = code;
  }
}

const GST_RATE_SET: ReadonlySet<number> = new Set(ALLOWED_LINE_GST_RATES);
const UQC_SET: ReadonlySet<string> = new Set(ALLOWED_UQC);

/**
 * Parse/validate a single stored-or-inbound quote line, tolerating BOTH the old shape
 * ({ sku, quantity, unitPrice, lineTotal }) and the new extended shape. A line with no new fields
 * normalises to a catalogue line (`source: "catalogue"`). Throws QuoteValidationError on a
 * structurally invalid line (custom/charge without name or a positive unitPrice, bad gstRate/hsn/uqc).
 */
export function parseQuoteProductLine(raw: unknown): QuoteProductLine {
  if (raw == null || typeof raw !== "object") {
    throw new QuoteValidationError("invalid_line", "Quote line must be an object.");
  }
  const r = raw as Record<string, unknown>;

  const sku = typeof r.sku === "string" ? r.sku : "";
  const quantity = Number(r.quantity ?? 0);
  const unitPrice = Number(r.unitPrice ?? 0);
  const lineTotal = Number(r.lineTotal ?? (Number.isFinite(unitPrice) && Number.isFinite(quantity) ? unitPrice * quantity : 0));

  const source: QuoteLineSource =
    r.source === "custom" || r.source === "charge" ? r.source : "catalogue";

  if (source === "catalogue" && sku === "") {
    throw new QuoteValidationError("missing_sku", "A catalogue line requires a sku.");
  }

  const line: QuoteProductLine = { sku, source, unitPrice, quantity, lineTotal };

  if (source === "custom" || source === "charge") {
    const name = typeof r.name === "string" ? r.name.trim() : "";
    if (name === "") {
      throw new QuoteValidationError("missing_name", `A ${source} line requires a name/description.`);
    }
    if (!Number.isFinite(unitPrice) || unitPrice <= 0) {
      throw new QuoteValidationError("invalid_unit_price", `A ${source} line requires a positive unit price.`);
    }
    line.name = name;
  } else if (typeof r.name === "string" && r.name.trim() !== "") {
    line.name = r.name.trim();
  }

  const effectiveQty = source === "charge" ? 1 : quantity;
  if (!Number.isFinite(effectiveQty) || effectiveQty <= 0) {
    throw new QuoteValidationError("invalid_quantity", `Line "${line.name ?? sku}" requires a positive quantity.`);
  }

  if (r.hsn != null && r.hsn !== "") {
    const hsn = String(r.hsn);
    if (!/^\d{4,8}$/.test(hsn)) {
      throw new QuoteValidationError("invalid_hsn", `HSN "${hsn}" must be 4–8 digits.`);
    }
    line.hsn = hsn;
  }
  if (r.gstRate != null) {
    const gstRate = Number(r.gstRate);
    if (!GST_RATE_SET.has(gstRate)) {
      throw new QuoteValidationError("invalid_gst_rate", `gstRate ${String(r.gstRate)} is not one of ${ALLOWED_LINE_GST_RATES.join(", ")}.`);
    }
    line.gstRate = gstRate;
  }
  if (r.uqc != null && r.uqc !== "") {
    const uqc = String(r.uqc);
    if (!UQC_SET.has(uqc)) {
      throw new QuoteValidationError("invalid_uqc", `uqc "${uqc}" is not one of ${ALLOWED_UQC.join(", ")}.`);
    }
    line.uqc = uqc;
  }
  if (typeof r.notes === "string" && r.notes !== "") line.notes = r.notes;

  return line;
}

export interface Quote {
  id: string;
  quote_number: string;
  status: QuoteStatus;
  created_at: string;
  valid_until: string | null;
  client_name: string;
  client_company: string;
  client_email: string;
  client_phone: string;
  occasion: string;
  kit_count: number;
  packaging_tier: string;
  personalisation_level: string;
  resume_intelligence: boolean;
  rush_order: boolean;
  rush_days: number | null;
  timeline: string | null;
  sample_message: string | null;
  special_instructions: string | null;
  products: QuoteProductLine[];
  pricing: PricingResult;
  discount_percent: number;
  discount_amount: number;
  final_total: number;
  per_kit_investment: number;
  validity_days: number;
  notes: string | null;
  pdf_url: string | null;
}

/* eslint-disable @typescript-eslint/no-explicit-any */
function mapRow(row: any): Quote {
  const pricing: PricingResult = row.pricing ?? ({} as PricingResult);
  return {
    id: row.id,
    quote_number: row.quote_number,
    status: row.status,
    created_at: row.created_at,
    valid_until: row.valid_until,
    client_name: row.client_name ?? "",
    client_company: row.client_company ?? "",
    client_email: row.client_email ?? "",
    client_phone: row.client_phone ?? "",
    occasion: row.occasion ?? "",
    kit_count: row.kit_count ?? row.quantity ?? 1,
    packaging_tier: row.packaging_tier ?? "standard",
    personalisation_level: row.personalisation_level ?? "name_occasion",
    resume_intelligence: Boolean(row.resume_intelligence),
    rush_order: Boolean(row.rush_order),
    rush_days: row.rush_days ?? null,
    timeline: row.timeline ?? null,
    sample_message: row.sample_message ?? null,
    special_instructions: row.special_instructions ?? null,
    products: (row.products ?? []) as QuoteProductLine[],
    pricing,
    discount_percent: Number(row.discount_percent ?? 0),
    discount_amount: Number(row.discount_amount ?? 0),
    final_total: Number(row.final_total ?? row.total_amount ?? 0),
    per_kit_investment: Number(row.per_kit_investment ?? pricing.perKitInvestment ?? 0),
    validity_days: row.validity_days ?? 15,
    notes: row.notes ?? null,
    pdf_url: row.pdf_url ?? null,
  };
}
/* eslint-enable @typescript-eslint/no-explicit-any */

function buildInsertPayload(input: QuoteInput, pricing: PricingResult) {
  const validityDays = input.validityDays ?? 15;
  const validUntil = new Date(Date.now() + validityDays * 86400000)
    .toISOString()
    .slice(0, 10);
  const discountPercent = input.discountPercent ?? 0;
  const discountAmount = Math.round((pricing.grandTotal * discountPercent) / 100);
  const finalTotal = pricing.grandTotal - discountAmount;
  const perKit = Math.round(finalTotal / Math.max(1, input.kitCount));

  const products: QuoteProductLine[] = pricing.lineItems.map((li) => {
    // Catalogue lines keep the pre-5A shape ({sku,quantity,unitPrice,lineTotal}) for back-compat;
    // custom/charge lines additionally persist source + name (+ any tax metadata) so they can be
    // reconstructed on load/duplicate without a catalogue lookup.
    const line: QuoteProductLine = {
      sku: li.sku,
      quantity: li.quantity,
      unitPrice: li.unitPrice,
      lineTotal: li.lineTotal,
    };
    if (li.source !== "catalogue") {
      line.source = li.source;
      line.name = li.productName;
    }
    if (li.hsn != null) line.hsn = li.hsn;
    if (li.gstRate != null) line.gstRate = li.gstRate;
    if (li.uqc != null) line.uqc = li.uqc;
    if (li.notes != null) line.notes = li.notes;
    return line;
  });

  return {
    payload: {
      client_name: input.clientName,
      client_company: input.clientCompany,
      client_email: input.clientEmail,
      client_phone: input.clientPhone,
      occasion: input.occasion,
      kit_count: input.kitCount,
      quantity: input.kitCount,
      packaging_tier: input.packagingTier,
      personalisation_level: input.personalisation,
      resume_intelligence: input.resumeIntelligence,
      rush_order: input.rushOrder,
      rush_days: input.rushDays ?? null,
      sample_message: input.sampleMessage ?? null,
      special_instructions: input.specialInstructions ?? null,
      products,
      pricing,
      discount_percent: discountPercent,
      discount_amount: discountAmount,
      final_total: finalTotal,
      per_kit_investment: perKit,
      validity_days: validityDays,
      valid_until: validUntil,
      notes: input.notes ?? null,
      status: "draft" as const,
      // Legacy numeric mirrors for coherence
      subtotal: pricing.subtotal,
      packaging_cost: pricing.packagingTotal,
      rush_surcharge: pricing.rushSurchargeAmount,
      total_amount: finalTotal,
    },
    finalTotal,
  };
}

export async function createQuote(input: QuoteInput): Promise<Quote> {
  const pricing = await calculatePricing({
    products: input.products,
    kitCount: input.kitCount,
    packagingTier: input.packagingTier,
    rushOrder: input.rushOrder,
    rushDays: input.rushDays,
    personalisation: input.personalisation,
    resumeIntelligence: input.resumeIntelligence,
  });
  const { payload } = buildInsertPayload(input, pricing);
  const supa = await userDb();
  const { data, error } = await supa.from("quotes").insert(payload).select("*").single();
  if (error) throw new Error(`Create quote failed: ${error.message}`);
  return mapRow(data);
}

export async function getQuote(id: string): Promise<Quote | null> {
  const supa = await userDb();
  const { data, error } = await supa.from("quotes").select("*").eq("id", id).maybeSingle();
  if (error) throw new Error(`Get quote failed: ${error.message}`);
  return data ? mapRow(data) : null;
}

export async function getQuoteByNumber(quoteNumber: string): Promise<Quote | null> {
  const supa = await userDb();
  const { data, error } = await supa
    .from("quotes")
    .select("*")
    .eq("quote_number", quoteNumber)
    .maybeSingle();
  if (error) throw new Error(`Get quote failed: ${error.message}`);
  return data ? mapRow(data) : null;
}

export interface QuoteFilters {
  status?: QuoteStatus;
  clientCompany?: string;
  from?: string;
  to?: string;
}

export async function listQuotes(filters: QuoteFilters = {}): Promise<Quote[]> {
  const supa = await userDb();
  let q = supa.from("quotes").select("*").order("created_at", { ascending: false });
  if (filters.status) q = q.eq("status", filters.status);
  if (filters.clientCompany) q = q.ilike("client_company", `%${filters.clientCompany}%`);
  if (filters.from) q = q.gte("created_at", filters.from);
  if (filters.to) q = q.lte("created_at", filters.to);
  const { data, error } = await q;
  if (error) throw new Error(`List quotes failed: ${error.message}`);
  return (data ?? []).map(mapRow);
}

export async function updateQuoteStatus(id: string, status: QuoteStatus): Promise<void> {
  const supa = await userDb();
  const stamp =
    status === "sent"
      ? { sent_at: new Date().toISOString() }
      : status === "viewed"
        ? { viewed_at: new Date().toISOString() }
        : status === "accepted"
          ? { accepted_at: new Date().toISOString() }
          : {};
  const { error } = await supa.from("quotes").update({ status, ...stamp }).eq("id", id);
  if (error) throw new Error(`Update status failed: ${error.message}`);

  // Prompt 7a reversal: a cancelled/rejected quote with NO order = a fallen-through gift ->
  // CLEAR occasion_gift_state so 6b escalation RESUMES. Service-role (system signal); only clears
  // rows with order_id NULL (a converted-to-order gift is committed and persists).
  if (status === "cancelled" || status === "rejected") {
    try {
      const { createAdminClient } = await import("@/lib/supabase/admin");
      const { clearGiftChosenForQuote } = await import("@/lib/engines/notifications");
      await clearGiftChosenForQuote(createAdminClient(), id);
    } catch (e) {
      console.error("[quote.updateQuoteStatus] gift-state reversal failed:", e);
    }
  }
}

/** Reconstructs a QuoteInput from a stored quote (for update/duplicate). */
function quoteToInput(quote: Quote): QuoteInput {
  return {
    clientName: quote.client_name,
    clientCompany: quote.client_company,
    clientEmail: quote.client_email,
    clientPhone: quote.client_phone,
    occasion: quote.occasion,
    products: quote.products.map((p) => {
      const src: QuoteLineSource = p.source ?? "catalogue";
      const line: PricingProductInput = { sku: p.sku, quantity: p.quantity, source: src };
      // Custom/charge lines carry their own price + name (no catalogue lookup); catalogue lines are
      // re-priced from the DB on duplicate/update, so we do NOT freeze their unitPrice here.
      if (src !== "catalogue") {
        line.name = p.name;
        line.unitPrice = p.unitPrice;
      }
      if (p.hsn != null) line.hsn = p.hsn;
      if (p.gstRate != null) line.gstRate = p.gstRate;
      if (p.uqc != null) line.uqc = p.uqc;
      if (p.notes != null) line.notes = p.notes;
      return line;
    }),
    packagingTier: quote.packaging_tier as PackagingTierId,
    personalisation: quote.personalisation_level as PersonalisationLevelId,
    resumeIntelligence: quote.resume_intelligence,
    rushOrder: quote.rush_order,
    rushDays: quote.rush_days ?? undefined,
    timeline: quote.timeline ?? undefined,
    sampleMessage: quote.sample_message ?? undefined,
    specialInstructions: quote.special_instructions ?? undefined,
    kitCount: quote.kit_count,
    validityDays: quote.validity_days,
    notes: quote.notes ?? undefined,
    discountPercent: quote.discount_percent,
  };
}

export async function updateQuote(id: string, updates: Partial<QuoteInput>): Promise<Quote> {
  const existing = await getQuote(id);
  if (!existing) throw new Error("Quote not found");
  const merged: QuoteInput = { ...quoteToInput(existing), ...updates };

  const pricing = await calculatePricing({
    products: merged.products,
    kitCount: merged.kitCount,
    packagingTier: merged.packagingTier,
    rushOrder: merged.rushOrder,
    rushDays: merged.rushDays,
    personalisation: merged.personalisation,
    resumeIntelligence: merged.resumeIntelligence,
  });
  const { payload } = buildInsertPayload(merged, pricing);
  const supa = await userDb();
  const { data, error } = await supa.from("quotes").update(payload).eq("id", id).select("*").single();
  if (error) throw new Error(`Update quote failed: ${error.message}`);
  return mapRow(data);
}

export async function duplicateQuote(id: string): Promise<Quote> {
  const existing = await getQuote(id);
  if (!existing) throw new Error("Quote not found");
  return createQuote(quoteToInput(existing));
}

export async function setQuotePdfUrl(id: string, url: string): Promise<void> {
  const supa = await userDb();
  const { error } = await supa.from("quotes").update({ pdf_url: url }).eq("id", id);
  if (error) throw new Error(`Set pdf_url failed: ${error.message}`);
}

// Request-scoped RLS client, imported dynamically so this server-only engine
// can be imported by client components (for its exported types) without
// pulling `next/headers` into the client bundle.
async function userDb() {
  const { createClient } = await import("@/lib/supabase/server");
  return createClient();
}
