/**
 * Quote Engine - INTERNAL USE ONLY (server-side).
 * Orchestrates pricing + persistence. Quote numbers are generated by the
 * `set_quote_number` DB trigger (format NV-Q-YYYY-NNNN).
 *
 * Prompt 2 (item 6): switched from the service-role client to the request-scoped
 * RLS client (`createClient`). All callers are authenticated (platform staff via
 * the /ops quote screens); RLS `quotes_read` + `quotes_write_*` policies scope
 * access, and `authorize()` at the route layer is the role gate. The
 * request-scoped client is imported DYNAMICALLY (see `userDb`) so this server
 * engine stays import-safe from client components that use its exported types.
 */
import {
  calculatePricing,
  type PackagingTierId,
  type PersonalisationLevelId,
  type PricingResult,
} from "@/lib/engines/pricing";

export type QuoteStatus =
  | "draft"
  | "sent"
  | "viewed"
  | "accepted"
  | "rejected"
  | "expired"
  | "converted"
  | "cancelled";

export interface QuoteInput {
  clientName: string;
  clientCompany: string;
  clientEmail: string;
  clientPhone: string;
  occasion: string;
  products: Array<{ sku: string; quantity: number }>;
  packagingTier: PackagingTierId;
  personalisation: PersonalisationLevelId;
  resumeIntelligence: boolean;
  rushOrder: boolean;
  rushDays?: number;
  timeline?: string;
  sampleMessage?: string;
  specialInstructions?: string;
  kitCount: number;
  validityDays?: number;
  notes?: string;
  discountPercent?: number;
  discountReason?: string;
}

export interface QuoteProductLine {
  sku: string;
  quantity: number;
  unitPrice: number;
  lineTotal: number;
}

export interface Quote {
  id: string;
  quote_number: string;
  status: QuoteStatus;
  created_at: string;
  valid_until: string | null;
  client_name: string;
  client_company: string;
  client_email: string;
  client_phone: string;
  occasion: string;
  kit_count: number;
  packaging_tier: string;
  personalisation_level: string;
  resume_intelligence: boolean;
  rush_order: boolean;
  rush_days: number | null;
  timeline: string | null;
  sample_message: string | null;
  special_instructions: string | null;
  products: QuoteProductLine[];
  pricing: PricingResult;
  discount_percent: number;
  discount_amount: number;
  final_total: number;
  per_kit_investment: number;
  validity_days: number;
  notes: string | null;
  pdf_url: string | null;
}

/* eslint-disable @typescript-eslint/no-explicit-any */
function mapRow(row: any): Quote {
  const pricing: PricingResult = row.pricing ?? ({} as PricingResult);
  return {
    id: row.id,
    quote_number: row.quote_number,
    status: row.status,
    created_at: row.created_at,
    valid_until: row.valid_until,
    client_name: row.client_name ?? "",
    client_company: row.client_company ?? "",
    client_email: row.client_email ?? "",
    client_phone: row.client_phone ?? "",
    occasion: row.occasion ?? "",
    kit_count: row.kit_count ?? row.quantity ?? 1,
    packaging_tier: row.packaging_tier ?? "standard",
    personalisation_level: row.personalisation_level ?? "name_occasion",
    resume_intelligence: Boolean(row.resume_intelligence),
    rush_order: Boolean(row.rush_order),
    rush_days: row.rush_days ?? null,
    timeline: row.timeline ?? null,
    sample_message: row.sample_message ?? null,
    special_instructions: row.special_instructions ?? null,
    products: (row.products ?? []) as QuoteProductLine[],
    pricing,
    discount_percent: Number(row.discount_percent ?? 0),
    discount_amount: Number(row.discount_amount ?? 0),
    final_total: Number(row.final_total ?? row.total_amount ?? 0),
    per_kit_investment: Number(row.per_kit_investment ?? pricing.perKitInvestment ?? 0),
    validity_days: row.validity_days ?? 15,
    notes: row.notes ?? null,
    pdf_url: row.pdf_url ?? null,
  };
}
/* eslint-enable @typescript-eslint/no-explicit-any */

function buildInsertPayload(input: QuoteInput, pricing: PricingResult) {
  const validityDays = input.validityDays ?? 15;
  const validUntil = new Date(Date.now() + validityDays * 86400000)
    .toISOString()
    .slice(0, 10);
  const discountPercent = input.discountPercent ?? 0;
  const discountAmount = Math.round((pricing.grandTotal * discountPercent) / 100);
  const finalTotal = pricing.grandTotal - discountAmount;
  const perKit = Math.round(finalTotal / Math.max(1, input.kitCount));

  const products: QuoteProductLine[] = pricing.lineItems.map((li) => ({
    sku: li.sku,
    quantity: li.quantity,
    unitPrice: li.unitPrice,
    lineTotal: li.lineTotal,
  }));

  return {
    payload: {
      client_name: input.clientName,
      client_company: input.clientCompany,
      client_email: input.clientEmail,
      client_phone: input.clientPhone,
      occasion: input.occasion,
      kit_count: input.kitCount,
      quantity: input.kitCount,
      packaging_tier: input.packagingTier,
      personalisation_level: input.personalisation,
      resume_intelligence: input.resumeIntelligence,
      rush_order: input.rushOrder,
      rush_days: input.rushDays ?? null,
      sample_message: input.sampleMessage ?? null,
      special_instructions: input.specialInstructions ?? null,
      products,
      pricing,
      discount_percent: discountPercent,
      discount_amount: discountAmount,
      final_total: finalTotal,
      per_kit_investment: perKit,
      validity_days: validityDays,
      valid_until: validUntil,
      notes: input.notes ?? null,
      status: "draft" as const,
      // Legacy numeric mirrors for coherence
      subtotal: pricing.subtotal,
      packaging_cost: pricing.packagingTotal,
      rush_surcharge: pricing.rushSurchargeAmount,
      total_amount: finalTotal,
    },
    finalTotal,
  };
}

export async function createQuote(input: QuoteInput): Promise<Quote> {
  const pricing = await calculatePricing({
    products: input.products,
    kitCount: input.kitCount,
    packagingTier: input.packagingTier,
    rushOrder: input.rushOrder,
    rushDays: input.rushDays,
    personalisation: input.personalisation,
    resumeIntelligence: input.resumeIntelligence,
  });
  const { payload } = buildInsertPayload(input, pricing);
  const supa = await userDb();
  const { data, error } = await supa.from("quotes").insert(payload).select("*").single();
  if (error) throw new Error(`Create quote failed: ${error.message}`);
  return mapRow(data);
}

export async function getQuote(id: string): Promise<Quote | null> {
  const supa = await userDb();
  const { data, error } = await supa.from("quotes").select("*").eq("id", id).maybeSingle();
  if (error) throw new Error(`Get quote failed: ${error.message}`);
  return data ? mapRow(data) : null;
}

export async function getQuoteByNumber(quoteNumber: string): Promise<Quote | null> {
  const supa = await userDb();
  const { data, error } = await supa
    .from("quotes")
    .select("*")
    .eq("quote_number", quoteNumber)
    .maybeSingle();
  if (error) throw new Error(`Get quote failed: ${error.message}`);
  return data ? mapRow(data) : null;
}

export interface QuoteFilters {
  status?: QuoteStatus;
  clientCompany?: string;
  from?: string;
  to?: string;
}

export async function listQuotes(filters: QuoteFilters = {}): Promise<Quote[]> {
  const supa = await userDb();
  let q = supa.from("quotes").select("*").order("created_at", { ascending: false });
  if (filters.status) q = q.eq("status", filters.status);
  if (filters.clientCompany) q = q.ilike("client_company", `%${filters.clientCompany}%`);
  if (filters.from) q = q.gte("created_at", filters.from);
  if (filters.to) q = q.lte("created_at", filters.to);
  const { data, error } = await q;
  if (error) throw new Error(`List quotes failed: ${error.message}`);
  return (data ?? []).map(mapRow);
}

export async function updateQuoteStatus(id: string, status: QuoteStatus): Promise<void> {
  const supa = await userDb();
  const stamp =
    status === "sent"
      ? { sent_at: new Date().toISOString() }
      : status === "viewed"
        ? { viewed_at: new Date().toISOString() }
        : status === "accepted"
          ? { accepted_at: new Date().toISOString() }
          : {};
  const { error } = await supa.from("quotes").update({ status, ...stamp }).eq("id", id);
  if (error) throw new Error(`Update status failed: ${error.message}`);
}

/** Reconstructs a QuoteInput from a stored quote (for update/duplicate). */
function quoteToInput(quote: Quote): QuoteInput {
  return {
    clientName: quote.client_name,
    clientCompany: quote.client_company,
    clientEmail: quote.client_email,
    clientPhone: quote.client_phone,
    occasion: quote.occasion,
    products: quote.products.map((p) => ({ sku: p.sku, quantity: p.quantity })),
    packagingTier: quote.packaging_tier as PackagingTierId,
    personalisation: quote.personalisation_level as PersonalisationLevelId,
    resumeIntelligence: quote.resume_intelligence,
    rushOrder: quote.rush_order,
    rushDays: quote.rush_days ?? undefined,
    timeline: quote.timeline ?? undefined,
    sampleMessage: quote.sample_message ?? undefined,
    specialInstructions: quote.special_instructions ?? undefined,
    kitCount: quote.kit_count,
    validityDays: quote.validity_days,
    notes: quote.notes ?? undefined,
    discountPercent: quote.discount_percent,
  };
}

export async function updateQuote(id: string, updates: Partial<QuoteInput>): Promise<Quote> {
  const existing = await getQuote(id);
  if (!existing) throw new Error("Quote not found");
  const merged: QuoteInput = { ...quoteToInput(existing), ...updates };

  const pricing = await calculatePricing({
    products: merged.products,
    kitCount: merged.kitCount,
    packagingTier: merged.packagingTier,
    rushOrder: merged.rushOrder,
    rushDays: merged.rushDays,
    personalisation: merged.personalisation,
    resumeIntelligence: merged.resumeIntelligence,
  });
  const { payload } = buildInsertPayload(merged, pricing);
  const supa = await userDb();
  const { data, error } = await supa.from("quotes").update(payload).eq("id", id).select("*").single();
  if (error) throw new Error(`Update quote failed: ${error.message}`);
  return mapRow(data);
}

export async function duplicateQuote(id: string): Promise<Quote> {
  const existing = await getQuote(id);
  if (!existing) throw new Error("Quote not found");
  return createQuote(quoteToInput(existing));
}

export async function setQuotePdfUrl(id: string, url: string): Promise<void> {
  const supa = await userDb();
  const { error } = await supa.from("quotes").update({ pdf_url: url }).eq("id", id);
  if (error) throw new Error(`Set pdf_url failed: ${error.message}`);
}

// Request-scoped RLS client, imported dynamically so this server-only engine
// can be imported by client components (for its exported types) without
// pulling `next/headers` into the client bundle.
async function userDb() {
  const { createClient } = await import("@/lib/supabase/server");
  return createClient();
}
