/**
 * Property-based tests for the pure derivation helpers of the catalogue
 * generator (`scripts/generate-catalog.ts`).
 *
 * Feature: image-catalog-rebuild — Properties 12, 13, 14, 16.
 *
 * These properties are validated both directly (against the exported pure
 * helpers `deriveTags`, `inferPersonalisation`, `deriveMilestone`) and
 * end-to-end (against the products produced by `buildCatalog`). Every fixture
 * is a synthetic in-memory {@link ImageManifest} generated by fast-check — no
 * test depends on a real `scripts/image-manifest.json`.
 *
 *   - Property 12: Exactly the first two products of each collection are
 *     featured.                                    (Validates: Requirements 14.5)
 *   - Property 13: Marketing tags obey the controlled-vocabulary rules.
 *          (Validates: Requirements 12.1, 12.2, 12.3, 12.4, 12.5, 12.6, 12.7)
 *   - Property 14: Personalisation is inferred for every product.
 *                                                  (Validates: Requirements 14.4)
 *   - Property 16: Milestone tenure is set exactly for collection B.
 *                                                  (Validates: Requirements 15.2)
 *
 * Each property runs >= 100 iterations via fast-check.
 */

import { describe, it, expect } from "vitest";
import fc from "fast-check";

import type { BucketCode, MilestoneTenure } from "../src/lib/types/product";
import type { ImageManifest, ManifestProduct } from "./restructure-images";
import {
  buildCatalog,
  deriveMilestone,
  deriveTags,
  inferPersonalisation,
  MARKETING_TAGS,
} from "./generate-catalog";

const NUM_RUNS = 200;

/* -------------------------------------------------------------------------- */
/* Fixed domains                                                              */
/* -------------------------------------------------------------------------- */

/** The eleven collection letters `"A"`–`"K"`. */
const LETTERS: readonly BucketCode[] = [
  "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K",
];

/** The three collection-`B` milestone tenures. */
const TENURES: readonly MilestoneTenure[] = ["1-year", "5-year", "10-year"];

/**
 * Name-token vocabulary that deliberately exercises the tag rules:
 *   - premium materials (copper / brass / leather / crystal) — Req 12.4;
 *   - employee-favourite types (bottle / mug / tote / tee / hoodie) — Req 12.5;
 *   - best-seller signals (hamper / curated / box) — Req 12.7;
 *   - neutral nouns that trigger none of the keyword rules.
 * Every token is alphabetic, so any non-empty combination cleans to a
 * non-empty product name (keeping `buildCatalog`'s non-empty guarantees happy).
 */
const NAME_WORDS: readonly string[] = [
  // premium materials (Req 12.4)
  "copper", "brass", "leather", "crystal",
  // employee-favourite types (Req 12.5)
  "bottle", "mug", "tote", "tee", "hoodie",
  // best-seller signals (Req 12.7)
  "hamper", "curated", "box",
  // neutral (trigger no keyword rule)
  "gift", "pen", "notebook", "candle", "frame", "clock",
  "desk", "plant", "award", "journal", "stand",
];

/* -------------------------------------------------------------------------- */
/* Arbitraries                                                                */
/* -------------------------------------------------------------------------- */

const LOWER_ALNUM = "abcdefghijklmnopqrstuvwxyz0123456789".split("");

/** A non-empty lowercase-alphanumeric slug token, e.g. `"a1b2"`. */
const slugTokenArb: fc.Arbitrary<string> = fc
  .array(fc.constantFrom(...LOWER_ALNUM), { minLength: 1, maxLength: 8 })
  .map((chars) => chars.join(""));

/** A relative storage image path, e.g. `"prod/img.webp"`. */
const imagePathArb: fc.Arbitrary<string> = fc
  .tuple(slugTokenArb, slugTokenArb, fc.constantFrom("webp", "jpg", "jpeg", "avif", "png"))
  .map(([dir, base, ext]) => `${dir}/${base}.${ext}`);

/** A raw source name (1–4 vocabulary words joined by spaces). */
const rawNameArb: fc.Arbitrary<string> = fc
  .array(fc.constantFrom(...NAME_WORDS), { minLength: 1, maxLength: 4 })
  .map((words) => words.join(" "));

/**
 * A synthetic {@link ManifestProduct}. Collection `B` always carries a tenure
 * (as the restructure step guarantees for real manifests); other collections
 * occasionally carry a stray tenure to prove `deriveMilestone` drops it.
 */
const manifestProductArb: fc.Arbitrary<ManifestProduct> = fc
  .record({
    collectionLetter: fc.constantFrom(...LETTERS),
    storageSlug: slugTokenArb,
    productSlug: slugTokenArb,
    sourcePath: rawNameArb,
    variantSets: fc.constant<string[]>([]),
    images: fc.array(imagePathArb, { minLength: 1, maxLength: 5 }),
  })
  .chain((base) =>
    base.collectionLetter === "B"
      ? fc.constantFrom(...TENURES).map((milestone) => ({ ...base, milestone }))
      : fc
          .option(fc.constantFrom(...TENURES), { nil: undefined })
          .map((milestone) =>
            milestone === undefined ? base : { ...base, milestone },
          ),
  );

/** Wrap manifest products into a full, minimal {@link ImageManifest}. */
function makeManifest(products: ManifestProduct[]): ImageManifest {
  return {
    generatedAt: new Date(0).toISOString(),
    source: "neonvisualsfinal",
    folderCounts: {},
    products,
    kitHeroImages: [],
    summary: {
      foldersProcessed: 0,
      filesCopied: 0,
      filesSkippedMp4: 0,
      filesSkippedOther: 0,
      errors: 0,
      unmatchedTopLevelFolders: [],
    },
  };
}

/** A non-empty manifest fixture (1–12 products spread across collections). */
const manifestArb: fc.Arbitrary<ImageManifest> = fc
  .array(manifestProductArb, { minLength: 1, maxLength: 12 })
  .map(makeManifest);

/* -------------------------------------------------------------------------- */
/* Tag-rule oracle (independent re-statement of Requirement 12)               */
/* -------------------------------------------------------------------------- */

const PREMIUM_RE = /\b(?:copper|brass|leather|crystal)\b/;
const FAVOURITE_RE = /\b(?:bottles?|mugs?|totes?|tees?|t-?shirts?|hoodies?)\b/;
const BEST_SELLER_RE = /\b(?:hamper|curated|box(?:es)?)\b/;

/** The set of tags a correct implementation must emit for `(name, letter)`. */
function expectedTags(name: string, letter: BucketCode): Set<string> {
  const haystack = name.toLowerCase();
  const tags = new Set<string>(["Personalizable", "Made in India"]); // 12.2
  if (letter === "H") tags.add("Eco Friendly"); // 12.3
  if (PREMIUM_RE.test(haystack)) tags.add("Premium"); // 12.4
  if (FAVOURITE_RE.test(haystack)) tags.add("Employee Favourite"); // 12.5
  if (letter === "G") tags.add("New"); // 12.6
  if (BEST_SELLER_RE.test(haystack)) tags.add("Best Seller"); // 12.7
  return tags;
}

/** Assert the controlled-vocabulary rules hold for a product's tags. */
function assertTagRules(
  name: string,
  letter: BucketCode,
  tags: readonly string[],
): void {
  // 12.1 — every tag is drawn from the controlled vocabulary.
  for (const tag of tags) {
    expect(MARKETING_TAGS).toContain(tag);
  }
  // No duplicate tags.
  expect(new Set(tags).size).toBe(tags.length);
  // 12.2–12.7 — exact rule outcome (both directions).
  expect(new Set(tags)).toEqual(expectedTags(name, letter));
}

/* -------------------------------------------------------------------------- */
/* Property 12 — featured selection (Req 14.5)                                */
/* -------------------------------------------------------------------------- */

describe("Feature: image-catalog-rebuild, Property 12 — exactly the first two products of each collection are featured", () => {
  it("marks the first two products (catalogue order) of every collection featured, and every other product not", () => {
    fc.assert(
      fc.property(manifestArb, (manifest) => {
        const { products } = buildCatalog(manifest);

        // Group products by collection, preserving catalogue order.
        const byBucket = new Map<BucketCode, boolean[]>();
        for (const product of products) {
          const flags = byBucket.get(product.bucket) ?? [];
          flags.push(product.isFeatured === true);
          byBucket.set(product.bucket, flags);
        }

        for (const flags of byBucket.values()) {
          flags.forEach((isFeatured, index) => {
            // First two (index 0, 1) featured; all others not.
            expect(isFeatured).toBe(index < 2);
          });
          // At most two featured per collection.
          expect(flags.filter(Boolean).length).toBe(Math.min(2, flags.length));
        }
      }),
      { numRuns: NUM_RUNS },
    );
  });
});

/* -------------------------------------------------------------------------- */
/* Property 13 — marketing tags (Req 12.1–12.7)                               */
/* -------------------------------------------------------------------------- */

describe("Feature: image-catalog-rebuild, Property 13 — marketing tags obey the controlled-vocabulary rules", () => {
  it("deriveTags produces only vocabulary tags that satisfy every rule", () => {
    fc.assert(
      fc.property(rawNameArb, fc.constantFrom(...LETTERS), (name, letter) => {
        assertTagRules(name, letter, deriveTags(name, letter));
      }),
      { numRuns: NUM_RUNS },
    );
  });

  it("every built product's tags obey the controlled-vocabulary rules", () => {
    fc.assert(
      fc.property(manifestArb, (manifest) => {
        for (const product of buildCatalog(manifest).products) {
          expect(product.tags).toBeDefined();
          assertTagRules(product.name, product.bucket, product.tags ?? []);
        }
      }),
      { numRuns: NUM_RUNS },
    );
  });
});

/* -------------------------------------------------------------------------- */
/* Property 14 — personalisation inference (Req 14.4)                         */
/* -------------------------------------------------------------------------- */

describe("Feature: image-catalog-rebuild, Property 14 — personalisation is inferred for every product", () => {
  it("inferPersonalisation returns a non-empty method for any name", () => {
    fc.assert(
      fc.property(rawNameArb, (name) => {
        const method = inferPersonalisation(name);
        expect(typeof method).toBe("string");
        expect(method.length).toBeGreaterThan(0);
      }),
      { numRuns: NUM_RUNS },
    );
  });

  it("every built product has a non-empty personalisation consistent with the inference", () => {
    fc.assert(
      fc.property(manifestArb, (manifest) => {
        for (const product of buildCatalog(manifest).products) {
          expect(product.personalisation).toBeDefined();
          const personalisation = product.personalisation ?? "";
          expect(personalisation.length).toBeGreaterThan(0);
          // Consistent with the material/type keyword mapping.
          expect(personalisation).toBe(inferPersonalisation(product.name));
        }
      }),
      { numRuns: NUM_RUNS },
    );
  });
});

/* -------------------------------------------------------------------------- */
/* Property 16 — milestone tenure (Req 15.2)                                  */
/* -------------------------------------------------------------------------- */

describe("Feature: image-catalog-rebuild, Property 16 — milestone tenure is set exactly for collection B", () => {
  it("deriveMilestone returns the tenure for collection B and undefined for every other collection", () => {
    fc.assert(
      fc.property(
        fc.constantFrom(...LETTERS),
        fc.option(fc.constantFrom(...TENURES), { nil: undefined }),
        (letter, tenure) => {
          const milestone = deriveMilestone(letter, tenure);
          if (letter === "B") {
            expect(milestone).toBe(tenure);
          } else {
            expect(milestone).toBeUndefined();
          }
        },
      ),
      { numRuns: NUM_RUNS },
    );
  });

  it("built products carry a valid milestone iff they belong to collection B", () => {
    fc.assert(
      fc.property(manifestArb, (manifest) => {
        for (const product of buildCatalog(manifest).products) {
          if (product.bucket === "B") {
            expect(product.milestone).toBeDefined();
            expect(TENURES).toContain(product.milestone);
          } else {
            expect(product.milestone).toBeUndefined();
          }
        }
      }),
      { numRuns: NUM_RUNS },
    );
  });
});
