-- =============================================================================
-- Neon Visuals — Seed Collections I/J/K (004): bucket rows, image_url column,
-- and 29 new product SKUs.
-- Split from the enum extension (003) because a new enum value cannot be used in
-- the same transaction that adds it — 003 commits first, so 'I'/'J'/'K' are safe
-- to reference here.
-- Additive only (ALTER/INSERT). No DROP, no CREATE TABLE, RLS untouched.
-- Prices intentionally left NULL (the public site reads from static no-price data
-- files; these columns are internal-only and not yet priced for these SKUs).
-- =============================================================================

-- ---------- (a) Bucket rows (I/J/K) -----------------------------------------
INSERT INTO buckets (code, name, slug, description, purpose, primary_buyer, asp_range_min, asp_range_max, icon, sort_order, seo_title, seo_description, is_active) VALUES
('I', 'Events & General Gifts', 'events-general',
 'Versatile gifting for conferences, town halls, and everyday corporate moments.',
 'Gifts for every event and everyday moment', 'Admin/HR/Events', NULL, NULL,
 'PartyPopper', 9,
 'Corporate Event & General Gifts | Neon Visuals',
 'Personalised gifts for conferences, town halls, and general corporate occasions — useful, on-brand, and never generic.', true),
('J', 'College Events', 'college-events',
 'Personalised merch and awards for fests, convocations, and campus programs.',
 'Campus events done memorably', 'College/Event Committee', NULL, NULL,
 'GraduationCap', 10,
 'College Event Gifts & Custom Merch | Neon Visuals',
 'Custom merch, awards, and kits for college fests, convocations, and campus events. Personalised at scale.', true),
('K', 'Visiting Cards & Business Stationery', 'visiting-cards',
 'Premium business cards and stationery that make a first impression count.',
 'A first impression worth keeping', 'Founders/Sales/Admin', NULL, NULL,
 'Contact', 11,
 'Premium Visiting Cards & Business Stationery | Neon Visuals',
 'Premium personalised visiting cards, letterheads, and business stationery designed for a lasting first impression.', true)
ON CONFLICT (code) DO NOTHING;

-- ---------- (b) Products: prepare for real images (additive, nullable) ------
ALTER TABLE products ADD COLUMN IF NOT EXISTS image_url TEXT;

-- ---------- (c) Collection I — Events & General Gifts (NV-I01–NV-I13) --------
INSERT INTO products (sku, bucket_id, name, slug, tagline, description, who_is_it_for, insight, wow_score, cogs, price_single, price_bulk_25, price_bulk_100, margin_percent, lead_time_days, rush_lead_time_days, moq, materials, personalization_types, occasions, archetypes, tags, recommended_packaging, is_featured, is_bestseller, is_new, sort_order) VALUES
('NV-I01', (SELECT id FROM buckets WHERE code='I'), '3D Printed Photo Album', '3d-printed-photo-album', 'Memories in three dimensions', 'Custom 3D-printed photo album perfect for farewells, anniversaries, and birthdays. Each album features a sculptural cover with the recipient''s name and occasion date, housing carefully curated photo prints inside.', 'Teams marking a farewell, anniversary, or birthday', 'A sculptural keepsake gets displayed, not drawered.', 9, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['pla','photo-paper'], ARRAY['print']::personalization_type[], ARRAY['farewell','birthday']::occasion_type[], ARRAY['root','connector']::employee_archetype[], ARRAY['trending','instagram-inspired','photo','keepsake','desk-test','use:anniversary','pers:name','pers:date','pers:photos'], 'premium', false, false, true, 1),
('NV-I02', (SELECT id FROM buckets WHERE code='I'), 'Instant Fridge Magnet Set', 'instant-fridge-magnet-set', 'Stick the memories where you''ll see them daily', 'Custom-printed fridge magnets featuring team photos, event moments, or personalised illustrations. Premium magnetic backing with glossy/matte finish options.', 'Teams and event crews wanting a daily reminder', 'A magnet keeps the moment in view long after the event ends.', 6, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['magnet','photo-paper'], ARRAY['print']::personalization_type[], ARRAY['team_offsite','farewell']::occasion_type[], ARRAY['connector','creator']::employee_archetype[], ARRAY['fun','budget-friendly','photo','use:team-event','pers:photos','pers:name','pers:event-name'], 'standard', false, false, true, 2),
('NV-I03', (SELECT id FROM buckets WHERE code='I'), '3D Printed Calendar (Never-Expiring)', '3d-printed-calendar-never-expiring', 'A calendar that never goes out of date', 'Instagram-inspired perpetual desk calendar with 3D-printed geometric design. Manually adjustable date blocks that work year after year. Personalised with name and company logo.', 'Desk-bound professionals and gifting at scale', 'A perpetual calendar earns desk space every single year.', 8, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['pla'], ARRAY['print']::personalization_type[], ARRAY['custom','new_year']::occasion_type[], ARRAY['builder','minimalist']::employee_archetype[], ARRAY['trending','instagram-inspired','desk','perpetual','desk-test','use:desk-accessory','pers:name','pers:logo'], 'premium', false, false, true, 3),
('NV-I04', (SELECT id FROM buckets WHERE code='I'), 'Magnetic Fluid Bluetooth Speaker', 'magnetic-fluid-bluetooth-speaker', 'Sound meets science — mesmerising desk art that plays music', 'Ferrofluid dancing speaker that creates mesmerising liquid patterns synced to music. A conversation-starter desk piece that doubles as a premium Bluetooth speaker. Branded with subtle logo placement.', 'Top performers and tech-forward teams', 'A piece that dances to music is the desk object people film.', 10, NULL, NULL, NULL, NULL, NULL, 10, 5, 10, ARRAY['ferrofluid','glass','electronics'], ARRAY['laser_engrave','print']::personalization_type[], ARRAY['spot_award']::occasion_type[], ARRAY['achiever','builder']::employee_archetype[], ARRAY['trending','viral','tech','instagram-inspired','desk-test','use:tech-team','use:premium-general','pers:logo','pers:engraved-name-on-base'], 'flagship', true, false, true, 4),
('NV-I05', (SELECT id FROM buckets WHERE code='I'), 'Collapsible Silicone Bottle', 'collapsible-silicone-bottle', 'Full-size hydration, pocket-size convenience', 'BPA-free collapsible silicone water bottle that folds flat when empty. Perfect for travel, gym, and daily commute. Available in brand colours with name printing.', 'Travellers, commuters, and wellness-minded teams', 'A bottle that folds away gets carried everywhere.', 6, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['silicone'], ARRAY['print']::personalization_type[], ARRAY['custom']::occasion_type[], ARRAY['explorer','minimalist']::employee_archetype[], ARRAY['practical','travel','eco-friendly','use:travel','use:wellness','pers:name','pers:logo','pers:colour'], 'standard', false, false, true, 5),
('NV-I06', (SELECT id FROM buckets WHERE code='I'), 'Water Bottle with Built-in Phone Stand', 'water-bottle-with-built-in-phone-stand', 'Hydrate and hands-free — two essentials in one', 'Innovative stainless steel bottle with integrated phone stand on the cap. Perfect desk companion for video calls and daily hydration. Name engraved on body.', 'Hybrid workers and new joiners', 'Two daily needs in one object means it never leaves the desk.', 7, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['stainless-steel'], ARRAY['laser_engrave']::personalization_type[], ARRAY['onboarding','custom']::occasion_type[], ARRAY['builder','achiever']::employee_archetype[], ARRAY['trending','practical','dual-purpose','desk-test','use:desk-accessory','pers:name','pers:logo'], 'premium', false, false, true, 6),
('NV-I07', (SELECT id FROM buckets WHERE code='I'), 'Foldable Silicone Phone Stand', 'foldable-silicone-phone-stand', 'Your phone''s favourite resting place', 'Ultra-portable foldable phone stand in premium silicone. Adjustable angles, works with any phone, collapses flat for travel. Personalised with name or initials.', 'Everyone with a phone and a desk', 'Cheap to make, personal, and used every single day.', 5, NULL, NULL, NULL, NULL, NULL, 5, 3, 25, ARRAY['silicone'], ARRAY['print']::personalization_type[], ARRAY['custom']::occasion_type[], ARRAY['minimalist','builder']::employee_archetype[], ARRAY['budget-friendly','practical','travel','desk-test','use:budget','use:travel','pers:name','pers:initials'], 'standard', false, false, true, 7),
('NV-I08', (SELECT id FROM buckets WHERE code='I'), 'Book Lamp (Foldable)', 'book-lamp-foldable', 'A book that lights up the room — literally', 'Instagram-viral wooden book lamp that opens to reveal warm LED pages. Folds flat like a real book, opens 360° into a stunning lamp. Magnetic closure. Logo or name on cover via laser engraving.', 'Farewells and premium client moments', 'A gift that transforms is a gift people post.', 9, NULL, NULL, NULL, NULL, NULL, 10, 5, 10, ARRAY['wood','led'], ARRAY['laser_engrave']::personalization_type[], ARRAY['farewell','client_appreciation']::occasion_type[], ARRAY['creator','root']::employee_archetype[], ARRAY['trending','viral','instagram-inspired','decor','desk-test','use:premium-general','pers:name','pers:message','pers:logo'], 'premium', false, false, true, 8),
('NV-I09', (SELECT id FROM buckets WHERE code='I'), 'Jellyfish Mood Lamp', 'jellyfish-mood-lamp', 'Mesmerising motion for mindful desks', 'Colour-changing LED jellyfish aquarium lamp. Lifelike silicone jellyfish float in a sealed tank with soothing colour transitions. A premium desk piece that reduces stress and sparks conversation.', 'Client appreciation and wellness-led teams', 'Calming motion makes the desk a place people want to be.', 9, NULL, NULL, NULL, NULL, NULL, 10, 5, 10, ARRAY['acrylic','silicone','led'], ARRAY['laser_engrave']::personalization_type[], ARRAY['client_appreciation']::occasion_type[], ARRAY['creator','root']::employee_archetype[], ARRAY['trending','viral','wellness','decor','desk-test','use:premium-general','use:wellness','pers:engraved-nameplate-on-base'], 'premium', false, false, true, 9),
('NV-I10', (SELECT id FROM buckets WHERE code='I'), 'Travelling Dispenser Kit', 'travelling-dispenser-kit', 'Organised essentials for the corporate traveller', 'Compact travel-sized dispenser set for toiletries in a branded pouch. TSA-friendly sizes, leak-proof, reusable. Personalised pouch with name embroidery.', 'Frequent flyers and offsite-bound teams', 'Travel utility earns a permanent spot in the bag.', 5, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['silicone','fabric'], ARRAY['embroidery']::personalization_type[], ARRAY['team_offsite','custom']::occasion_type[], ARRAY['explorer','minimalist']::employee_archetype[], ARRAY['practical','travel','use:travel','pers:name','pers:logo'], 'standard', false, false, true, 10),
('NV-I11', (SELECT id FROM buckets WHERE code='I'), 'Desk Organiser Kit', 'desk-organiser-kit', 'Declutter the desk, elevate the vibe', 'Multi-compartment desk organiser in premium wood or acrylic. Holds pens, phone, cards, sticky notes, and small accessories. Laser-engraved name on front panel.', 'New joiners and desk-bound professionals', 'A tidy desk is a daily, visible win.', 7, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['wood','acrylic'], ARRAY['laser_engrave']::personalization_type[], ARRAY['onboarding','custom']::occasion_type[], ARRAY['builder','minimalist']::employee_archetype[], ARRAY['practical','desk','organisation','desk-test','use:desk-accessory','pers:name','pers:logo'], 'premium', false, false, true, 11),
('NV-I12', (SELECT id FROM buckets WHERE code='I'), 'Event T-Shirt / Hoodie', 'event-t-shirt-hoodie', 'Wear the moment, remember the team', 'Custom-designed event tees and hoodies with event name, date, and team member names. Premium cotton, DTF/screen print. Available in crew neck, V-neck, and hoodie options.', 'Hackathons, offsites, and team milestones', 'Wearable memory outlives any trophy.', 7, NULL, NULL, NULL, NULL, NULL, 10, 5, 25, ARRAY['cotton'], ARRAY['dtf','print']::personalization_type[], ARRAY['team_offsite','company_anniversary']::occasion_type[], ARRAY['connector','creator']::employee_archetype[], ARRAY['apparel','team-identity','use:hackathon','use:team-event','pers:name','pers:event-design','pers:team-names'], 'standard', false, false, true, 12),
('NV-I13', (SELECT id FROM buckets WHERE code='I'), 'Custom Cap (Embroidered)', 'custom-cap-embroidered', 'Top off the team spirit', 'Premium structured cap with embroidered logo and optional name on the side/back. Adjustable strap, breathable fabric. Perfect for offsites, sports days, and team identity.', 'Sports days, offsites, and team identity', 'Headwear turns a team into a visible tribe.', 5, NULL, NULL, NULL, NULL, NULL, 10, 5, 25, ARRAY['cotton'], ARRAY['embroidery']::personalization_type[], ARRAY['team_offsite']::occasion_type[], ARRAY['connector','explorer']::employee_archetype[], ARRAY['apparel','team-identity','budget-friendly','use:sports-day','use:team-event','pers:logo','pers:name','pers:event-text'], 'standard', false, false, true, 13);

-- ---------- (c) Collection J — College Events (NV-J01–NV-J08) ---------------
INSERT INTO products (sku, bucket_id, name, slug, tagline, description, who_is_it_for, insight, wow_score, cogs, price_single, price_bulk_25, price_bulk_100, margin_percent, lead_time_days, rush_lead_time_days, moq, materials, personalization_types, occasions, archetypes, tags, recommended_packaging, is_featured, is_bestseller, is_new, sort_order) VALUES
('NV-J01', (SELECT id FROM buckets WHERE code='J'), 'College Fest T-Shirt', 'college-fest-t-shirt', 'The tee that becomes the memory', 'Custom-designed fest/event t-shirt in premium 190 GSM cotton. Full-colour DTF print with event branding, date, and college identity. Bulk-friendly pricing without compromising print quality.', 'Fest committees and campus event teams', 'The fest tee becomes the keepsake of the whole event.', 7, NULL, NULL, NULL, NULL, NULL, 10, 5, 25, ARRAY['cotton'], ARRAY['dtf']::personalization_type[], ARRAY['custom']::occasion_type[], ARRAY['connector','creator']::employee_archetype[], ARRAY['apparel','college','volume','use:college-fest','use:hackathon','use:cultural-event','pers:event-design','pers:college-logo','pers:participant-name-optional'], 'standard', false, false, true, 1),
('NV-J02', (SELECT id FROM buckets WHERE code='J'), 'College Event Hoodie', 'college-event-hoodie', 'Cosy campus memories', 'Premium 300 GSM fleece hoodie with event/college branding. Embroidered or DTF print. The hoodie students actually keep wearing years after graduation.', 'Campus fests and winter events', 'The hoodie that students keep wearing after graduation.', 8, NULL, NULL, NULL, NULL, NULL, 10, 5, 25, ARRAY['cotton-fleece'], ARRAY['embroidery','dtf']::personalization_type[], ARRAY['custom']::occasion_type[], ARRAY['connector','creator']::employee_archetype[], ARRAY['apparel','college','premium','use:college-fest','use:hackathon','use:winter-event','pers:event-design','pers:college-logo'], 'standard', false, false, true, 2),
('NV-J03', (SELECT id FROM buckets WHERE code='J'), 'Event Cap', 'event-cap', 'Cap the experience', 'Structured cotton cap with embroidered college/event logo. Adjustable back strap. Available in 10+ colours. Bulk-order friendly.', 'Sports days and campus fests', 'A shared cap turns a crowd into one team.', 5, NULL, NULL, NULL, NULL, NULL, 10, 5, 25, ARRAY['cotton'], ARRAY['embroidery']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['connector','explorer']::employee_archetype[], ARRAY['apparel','college','budget-friendly','use:sports-day','use:college-fest','pers:logo','pers:event-text'], 'standard', false, false, true, 3),
('NV-J04', (SELECT id FROM buckets WHERE code='J'), 'Custom Tote Bag', 'custom-tote-bag', 'Carry the campus vibe everywhere', 'Heavy-duty canvas tote with screen-printed event art. Reinforced handles, internal pocket. Doubles as a daily-use bag long after the event.', 'Campus fests and hackathons', 'A daily-carry bag keeps the event alive on every commute.', 5, NULL, NULL, NULL, NULL, NULL, 10, 5, 25, ARRAY['canvas'], ARRAY['print']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['explorer','connector']::employee_archetype[], ARRAY['eco-friendly','college','practical','use:college-fest','use:hackathon','pers:event-design','pers:college-logo'], 'standard', false, false, true, 4),
('NV-J05', (SELECT id FROM buckets WHERE code='J'), 'Flexible Phone Stand', 'flexible-phone-stand', 'Bendy, fun, and endlessly useful', 'Flexible octopus-style phone holder that wraps around anything. Fun colours, compact, and universally useful. Branded with event/college logo.', 'Campus fests and hackathon goodie bags', 'A fun, useful gadget gets used long after the fest.', 6, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['silicone'], ARRAY['print']::personalization_type[], ARRAY['custom']::occasion_type[], ARRAY['builder','explorer']::employee_archetype[], ARRAY['budget-friendly','tech','fun','use:college-fest','use:hackathon','pers:logo','pers:colour'], 'standard', false, false, true, 5),
('NV-J06', (SELECT id FROM buckets WHERE code='J'), 'Eco-Friendly Kit (Bamboo Pen + Seed Paper Notebook + Jute Pouch)', 'eco-friendly-kit-bamboo-pen-seed-paper-notebook-jute-pouch', 'Green gifts for the next generation', 'Sustainability-focused combo kit: bamboo pen, plantable seed paper notebook, packed in a printed jute pouch. Perfect for eco-conscious campus events.', 'Eco-conscious campuses and environment-day events', 'A plantable kit turns a gift into a sustainability story.', 7, NULL, NULL, NULL, NULL, NULL, 10, 5, 25, ARRAY['bamboo','seed-paper','jute'], ARRAY['print']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['root','creator']::employee_archetype[], ARRAY['eco-friendly','college','kit','use:environment-day','use:college-fest','pers:college-logo','pers:event-name'], 'premium', false, false, true, 6),
('NV-J07', (SELECT id FROM buckets WHERE code='J'), 'Student Diary + Pen Combo', 'student-diary-pen-combo', 'Plan the future, one page at a time', 'A5 hardbound diary with academic year calendar, goal-setting pages, and college branding. Paired with a matching wooden/bamboo pen. Budget-friendly for large batches.', 'New academic year and orientation kits', 'A daily planner keeps the college brand in hand all year.', 6, NULL, NULL, NULL, NULL, NULL, 10, 5, 25, ARRAY['paper','bamboo'], ARRAY['print']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['scholar','builder']::employee_archetype[], ARRAY['stationery','college','practical','use:new-academic-year','use:hackathon','pers:college-logo','pers:year','pers:student-name-optional'], 'standard', false, false, true, 7),
('NV-J08', (SELECT id FROM buckets WHERE code='J'), 'College Notebook (Ruled/Blank)', 'college-notebook-ruled-blank', 'Notes worth keeping', 'Quality spiral or stitched notebook with custom-printed cover featuring event/college artwork. 80 GSM acid-free paper. Available in ruled, blank, and dot-grid.', 'Workshops and large campus batches', 'A great cover makes an everyday notebook worth keeping.', 4, NULL, NULL, NULL, NULL, NULL, 10, 5, 25, ARRAY['paper'], ARRAY['print']::personalization_type[], ARRAY['onboarding','custom']::occasion_type[], ARRAY['scholar','minimalist']::employee_archetype[], ARRAY['stationery','college','budget-friendly','use:workshop','pers:cover-design','pers:college-logo'], 'budget', false, false, true, 8);

-- ---------- (c) Collection K — Visiting Cards & Business Stationery (NV-K01–NV-K08)
INSERT INTO products (sku, bucket_id, name, slug, tagline, description, who_is_it_for, insight, wow_score, cogs, price_single, price_bulk_25, price_bulk_100, margin_percent, lead_time_days, rush_lead_time_days, moq, materials, personalization_types, occasions, archetypes, tags, recommended_packaging, is_featured, is_bestseller, is_new, sort_order) VALUES
('NV-K01', (SELECT id FROM buckets WHERE code='K'), 'Premium Visiting Card (Matte + Spot UV)', 'premium-visiting-card-matte-spot-uv', 'The handshake before the handshake', '350 GSM art card with matte lamination and spot UV on logo/name. Clean, professional, tactile. The industry standard elevated with premium finishing.', 'Professionals and teams refreshing their brand', 'The card is the first impression, so it should feel deliberate.', 6, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['art-card'], ARRAY['uv_print','print']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['minimalist','achiever']::employee_archetype[], ARRAY['stationery','professional','classic','use:professional','use:rebranding','pers:name','pers:designation','pers:contact','pers:company-branding'], 'standard', false, false, true, 1),
('NV-K02', (SELECT id FROM buckets WHERE code='K'), 'NFC Smart Business Card', 'nfc-smart-business-card', 'Tap. Connect. Impress.', 'Premium PVC or metal-finish card with embedded NFC chip. Tap any phone to instantly share your digital profile, LinkedIn, portfolio, or vCard. No app needed. The future of networking.', 'Founders, sales leaders, and tech teams', 'A tap-to-share card makes networking memorable and modern.', 9, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['pvc','nfc-chip'], ARRAY['print']::personalization_type[], ARRAY['custom']::occasion_type[], ARRAY['builder','connector']::employee_archetype[], ARRAY['tech-forward','premium','smart','networking','use:professional','use:tech-companies','use:events','use:cxo','pers:name','pers:designation','pers:digital-profile-link','pers:company-branding'], 'premium', false, false, true, 2),
('NV-K03', (SELECT id FROM buckets WHERE code='K'), 'Letterpress Visiting Card (Cotton Stock)', 'letterpress-visiting-card-cotton-stock', 'Feel the impression before you read the name', '600 GSM cotton stock with deep-debossed letterpress printing. Tactile luxury that people keep in their wallets instead of throwing away. For founders and CXOs who believe details matter.', 'Founders and CXOs who sweat the details', 'A tactile card is kept in the wallet, not the bin.', 9, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['cotton-paper'], ARRAY['deboss']::personalization_type[], ARRAY['custom']::occasion_type[], ARRAY['minimalist','achiever']::employee_archetype[], ARRAY['luxury','tactile','artisan','premium','use:cxo','use:founder','use:premium-professional','pers:name','pers:designation','pers:contact','pers:company-branding'], 'premium', false, false, true, 3),
('NV-K04', (SELECT id FROM buckets WHERE code='K'), 'Metal Business Card (SS/Brass)', 'metal-business-card-ss-brass', 'A card they''ll never throw away', 'Laser-engraved stainless steel or brass business card. Mirror or matte finish. Arrives in a velvet sleeve. A statement piece for leaders who want to be remembered.', 'Leaders who want to be remembered', 'A metal card is a statement nobody discards.', 10, NULL, NULL, NULL, NULL, NULL, 9, 5, 10, ARRAY['stainless-steel','brass'], ARRAY['laser_engrave']::personalization_type[], ARRAY['custom']::occasion_type[], ARRAY['achiever','minimalist']::employee_archetype[], ARRAY['luxury','metal','statement','premium','use:cxo','use:founder','use:luxury-professional','pers:name','pers:designation','pers:contact','pers:laser-engraved'], 'flagship', true, false, true, 4),
('NV-K05', (SELECT id FROM buckets WHERE code='K'), 'Seed Paper Visiting Card', 'seed-paper-visiting-card', 'Plant the connection', 'Handmade seed paper card embedded with wildflower or basil seeds. After use, plant it and watch it grow. Perfect for sustainability-focused companies and ESG-conscious professionals.', 'Sustainability-focused and ESG-conscious teams', 'A card that grows turns a contact into a story.', 7, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['seed-paper'], ARRAY['print']::personalization_type[], ARRAY['custom']::occasion_type[], ARRAY['root','creator']::employee_archetype[], ARRAY['eco-friendly','plantable','sustainable','use:eco-companies','use:csr','use:networking','pers:name','pers:designation','pers:contact','pers:seed-type'], 'premium', false, false, true, 5),
('NV-K06', (SELECT id FROM buckets WHERE code='K'), 'Transparent Acrylic Card', 'transparent-acrylic-card', 'Crystal clear first impression', 'Frosted or clear acrylic card with UV-printed details. Modern, standout, and impossible to ignore in a stack of paper cards. Comes in a protective sleeve.', 'Designers, tech teams, and creative professionals', 'A transparent card stands out in any stack.', 8, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['acrylic'], ARRAY['uv_print']::personalization_type[], ARRAY['custom']::occasion_type[], ARRAY['creator','builder']::employee_archetype[], ARRAY['modern','standout','creative','use:tech-companies','use:designers','use:creative-professionals','pers:name','pers:designation','pers:contact','pers:company-branding'], 'premium', false, false, true, 6),
('NV-K07', (SELECT id FROM buckets WHERE code='K'), 'Wooden Visiting Card (Laser-Engraved)', 'wooden-visiting-card-laser-engraved', 'Rooted in craftsmanship', 'Thin-cut premium wood veneer card with laser-engraved details. Natural grain makes every card unique. Sustainable, memorable, conversation-starting.', 'Eco-conscious founders and creative professionals', 'Natural grain makes every card one of a kind.', 8, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['wood-veneer'], ARRAY['laser_engrave']::personalization_type[], ARRAY['custom']::occasion_type[], ARRAY['root','creator']::employee_archetype[], ARRAY['eco-friendly','artisan','unique','use:eco-companies','use:creative-professionals','use:founders','pers:name','pers:designation','pers:contact','pers:laser-engraved'], 'premium', false, false, true, 7),
('NV-K08', (SELECT id FROM buckets WHERE code='K'), 'Business Stationery Kit (Cards + Letterhead + Envelope)', 'business-stationery-kit-cards-letterhead-envelope', 'Your complete brand identity, boxed', 'Full stationery suite: 200 visiting cards + 50 letterheads + 50 envelopes, all in matching premium paper stock with consistent brand design. Delivered in a branded keepsake box.', 'New companies and brands relaunching their identity', 'A matching suite signals a brand that has its act together.', 7, NULL, NULL, NULL, NULL, NULL, 10, 5, 10, ARRAY['paper'], ARRAY['print']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['builder','connector']::employee_archetype[], ARRAY['professional','complete-suite','branding','use:new-company','use:rebranding','pers:full-company-branding','pers:name','pers:designation'], 'premium', false, false, true, 8);

-- =============================================================================
-- End of migration 004
-- =============================================================================
