-- =============================================================================
-- Neon Visuals — Seed Remaining B–H Handbook SKUs (005): 46 new product SKUs.
-- Completes the handbook coverage for buckets B (Milestone), C (CEO/Leadership),
-- D (Festive/Seasonal), E (Client Appreciation), and H (Sustainability/Eco) by
-- adding the SKUs that the representative seed (seed.sql) left out.
-- Additive only (INSERT). No DROP, no ALTER, no CREATE TABLE — RLS untouched.
-- No existing rows are modified; each INSERT ends with ON CONFLICT (sku) DO NOTHING.
-- Prices intentionally left NULL (cogs, price_single, price_bulk_25,
-- price_bulk_100, margin_percent) — the public site reads from static no-price
-- data files; these columns are internal-only and not yet priced for these SKUs.
-- image_url is intentionally omitted (defaults to NULL).
-- =============================================================================

-- ---------- Bucket B — Milestone & Anniversary (NV-B05–NV-B15) --------------
INSERT INTO products (sku, bucket_id, name, slug, tagline, description, who_is_it_for, insight, wow_score, cogs, price_single, price_bulk_25, price_bulk_100, margin_percent, lead_time_days, rush_lead_time_days, moq, materials, personalization_types, occasions, archetypes, tags, recommended_packaging, is_featured, is_bestseller, is_new, sort_order) VALUES
('NV-B05', (SELECT id FROM buckets WHERE code='B'), '5-Year Crystal Award Name+Date', '5-year-crystal-award-name-date', 'Five years of brilliance, crystallised', 'Premium crystal award with 3D laser-engraved name and joining date. LED-lit base creates a luminous desk centrepiece that celebrates half a decade of commitment.', 'Teams marking a 5-year work anniversary', 'A lit award turns tenure into a daily, visible point of pride.', 8, NULL, NULL, NULL, NULL, NULL, 9, 5, 10, ARRAY['crystal','led'], ARRAY['laser_engrave']::personalization_type[], ARRAY['work_anniversary_5']::occasion_type[], ARRAY['achiever']::employee_archetype[], ARRAY['award','crystal','milestone','desk-test'], 'premium', false, false, true, 5),
('NV-B06', (SELECT id FROM buckets WHERE code='B'), '5-Year Leather Journal Numbered Edition', '5-year-leather-journal-numbered-edition', 'Five years of stories, bound in leather', 'Hand-numbered limited edition leather journal with the employee''s name debossed on cover. 200 pages of premium paper. A keepsake that honours five years of dedication.', 'Five-year milestones for makers and thinkers', 'A numbered edition makes the recipient feel rare, not routine.', 7, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['leather','paper'], ARRAY['deboss']::personalization_type[], ARRAY['work_anniversary_5']::occasion_type[], ARRAY['creator','scholar']::employee_archetype[], ARRAY['journal','leather','keepsake','desk-test'], 'standard', false, false, true, 6),
('NV-B07', (SELECT id FROM buckets WHERE code='B'), '5-Year Desk Clock Wood+Brass', '5-year-desk-clock-wood-brass', 'Every second counts — especially after five years', 'Handcrafted wooden desk clock with brass accents and engraved nameplate. A daily reminder of time well spent, crafted from sheesham wood by Saharanpur artisans.', 'Five-year milestones for desk-bound leaders', 'A working clock earns desk space that a trophy never will.', 8, NULL, NULL, NULL, NULL, NULL, 9, 5, 10, ARRAY['wood','brass'], ARRAY['laser_engrave']::personalization_type[], ARRAY['work_anniversary_5']::occasion_type[], ARRAY['achiever','scholar']::employee_archetype[], ARRAY['clock','desk','milestone','desk-test'], 'premium', false, false, true, 7),
('NV-B08', (SELECT id FROM buckets WHERE code='B'), '7-Year Marble Nameplate Office', '7-year-marble-nameplate-office', 'Your name, carved in stone — because you''ve earned it', 'Makrana marble office nameplate with brass inlay lettering. Jaipur-crafted statement piece for the desk of someone who has built their legacy at the company.', 'Seven-year milestones for senior team members', 'A stone nameplate signals permanence, not just presence.', 9, NULL, NULL, NULL, NULL, NULL, 9, 5, 10, ARRAY['marble','brass'], ARRAY['laser_engrave']::personalization_type[], ARRAY['work_anniversary_7']::occasion_type[], ARRAY['achiever']::employee_archetype[], ARRAY['nameplate','marble','desk','desk-test'], 'premium', false, false, true, 8),
('NV-B09', (SELECT id FROM buckets WHERE code='B'), '10-Year Copper Bar Set 4pc', '10-year-copper-bar-set-4pc', 'A decade calls for a toast', 'Premium copper bar set — 4 Moscow mule mugs with name engraving, presented in a wooden tray. Moradabad-crafted celebration set for a milestone worth raising a glass to.', 'Decade milestones for social, well-loved teammates', 'A shared toast turns a personal milestone into a team moment.', 9, NULL, NULL, NULL, NULL, NULL, 9, 5, 10, ARRAY['copper','wood'], ARRAY['laser_engrave']::personalization_type[], ARRAY['work_anniversary_10']::occasion_type[], ARRAY['connector','achiever']::employee_archetype[], ARRAY['barware','copper','milestone','desk-test'], 'flagship', false, false, true, 9),
('NV-B10', (SELECT id FROM buckets WHERE code='B'), '10-Year Illustrated Career Map', '10-year-illustrated-career-map', 'Your journey, illustrated — from Day 1 to Year 10', 'Custom-commissioned illustrated timeline mapping the employee''s entire career journey at the company. Key projects, promotions, team changes, and milestones — hand-drawn and framed. The most emotional gift in our catalog.', 'Decade milestones that deserve a story', 'A hand-drawn journey says we remembered every chapter.', 10, NULL, NULL, NULL, NULL, NULL, 9, 5, 10, ARRAY['paper','frame'], ARRAY['print']::personalization_type[], ARRAY['work_anniversary_10']::occasion_type[], ARRAY['creator','achiever']::employee_archetype[], ARRAY['illustration','keepsake','milestone','desk-test'], 'premium', false, false, true, 10),
('NV-B11', (SELECT id FROM buckets WHERE code='B'), '15-Year Brass Trophy Heritage', '15-year-brass-trophy-heritage', 'Fifteen years. Weighty. Significant. Permanent.', 'Solid brass trophy on marble base with engraved nameplate. Heavy in the hand because the achievement is heavy in meaning. A boardroom-grade statement of loyalty.', 'Fifteen-year milestones for long-tenure leaders', 'Real weight in the hand makes recognition feel earned.', 9, NULL, NULL, NULL, NULL, NULL, 9, 5, 10, ARRAY['brass','marble'], ARRAY['laser_engrave']::personalization_type[], ARRAY['work_anniversary_15']::occasion_type[], ARRAY['achiever']::employee_archetype[], ARRAY['award','brass','milestone','desk-test'], 'flagship', false, false, true, 11),
('NV-B12', (SELECT id FROM buckets WHERE code='B'), '20-Year Achievement Coin Die-Cast', '20-year-achievement-coin-die-cast', 'Two decades of excellence — minted in metal', 'Custom die-cast commemorative coin in gold finish, presented in velvet-lined case. Collector-grade heirloom piece with name, years, and company crest. Limited edition feel.', 'Twenty-year milestones worth immortalising', 'A minted coin reads as legacy, not just longevity.', 8, NULL, NULL, NULL, NULL, NULL, 9, 5, 10, ARRAY['metal','velvet'], ARRAY['laser_engrave']::personalization_type[], ARRAY['work_anniversary_20']::occasion_type[], ARRAY['achiever']::employee_archetype[], ARRAY['coin','heirloom','milestone','desk-test'], 'flagship', false, false, true, 12),
('NV-B13', (SELECT id FROM buckets WHERE code='B'), 'Milestone Hoodie Year Design', 'milestone-hoodie-year-design', 'Wear your years with pride', 'Premium embroidered hoodie featuring the milestone year in bold design. 300 GSM fleece, name on sleeve, year on chest. The hoodie that says ''I built this place.''', 'Culture-led teams celebrating tenure', 'Wearable recognition has a longer shelf life than a trophy.', 7, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['cotton-fleece'], ARRAY['embroidery']::personalization_type[], ARRAY['work_anniversary_3']::occasion_type[], ARRAY['connector','creator']::employee_archetype[], ARRAY['hoodie','wearable','milestone'], 'standard', false, false, true, 13),
('NV-B14', (SELECT id FROM buckets WHERE code='B'), 'Keepsake Box Sheesham Wood', 'keepsake-box-sheesham-wood', 'A box that holds more than objects — it holds memories', 'Hand-carved sheesham wood keepsake box with brass hinges and engraved lid. Designed to store all the small mementos from a career — badges, coins, cards, photos.', 'Milestone moments for sentimental keepers', 'A box for mementos makes every future memory feel worth saving.', 8, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['wood','brass'], ARRAY['laser_engrave']::personalization_type[], ARRAY['work_anniversary_5']::occasion_type[], ARRAY['scholar','creator']::employee_archetype[], ARRAY['keepsake','wood','milestone','desk-test'], 'standard', false, false, true, 14),
('NV-B15', (SELECT id FROM buckets WHERE code='B'), 'LED Light Box Name+Year+Message', 'led-light-box-name-year-message', 'Your name in lights — because you deserve the spotlight', 'Custom LED light box displaying employee name, milestone year, and a personal message. Warm white glow creates a desk centrepiece that''s impossible to ignore.', 'Milestone recognition for the whole team to see', 'A glowing name on the desk is recognition nobody can miss.', 8, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['led','acrylic'], ARRAY['print']::personalization_type[], ARRAY['work_anniversary_5']::occasion_type[], ARRAY['creator','connector']::employee_archetype[], ARRAY['led','desk','milestone','desk-test'], 'standard', false, false, true, 15)
ON CONFLICT (sku) DO NOTHING;

-- ---------- Bucket C — CEO & Leadership Recognition (NV-C05–NV-C12) ---------
INSERT INTO products (sku, bucket_id, name, slug, tagline, description, who_is_it_for, insight, wow_score, cogs, price_single, price_bulk_25, price_bulk_100, margin_percent, lead_time_days, rush_lead_time_days, moq, materials, personalization_types, occasions, archetypes, tags, recommended_packaging, is_featured, is_bestseller, is_new, sort_order) VALUES
('NV-C05', (SELECT id FROM buckets WHERE code='C'), 'Copper Whiskey Set 2+Tray', 'copper-whiskey-set-2-tray', 'Leadership deserves a proper toast', 'Hand-hammered copper whiskey glass set with matching tray. Name engraved on each glass. Moradabad-crafted celebration set for leaders who set the standard.', 'Spot awards for leaders who set the bar', 'A celebration object outlasts the moment it marks.', 9, NULL, NULL, NULL, NULL, NULL, 9, 5, 10, ARRAY['copper','wood'], ARRAY['laser_engrave']::personalization_type[], ARRAY['spot_award']::occasion_type[], ARRAY['achiever']::employee_archetype[], ARRAY['barware','copper','leadership','desk-test'], 'flagship', false, false, true, 5),
('NV-C06', (SELECT id FROM buckets WHERE code='C'), 'Achievement Coin Gold Velvet', 'achievement-coin-gold-velvet', 'A coin for the collection — and the legacy', 'Die-cast achievement coin in antique gold finish, presented in a velvet-lined display case. Company crest on one side, recipient''s name and achievement on the other.', 'Spot awards that deserve a keepsake', 'A coin in a case turns recognition into something collected.', 7, NULL, NULL, NULL, NULL, NULL, 9, 5, 10, ARRAY['metal','velvet'], ARRAY['laser_engrave']::personalization_type[], ARRAY['spot_award']::occasion_type[], ARRAY['achiever']::employee_archetype[], ARRAY['coin','keepsake','leadership','desk-test'], 'premium', false, false, true, 6),
('NV-C07', (SELECT id FROM buckets WHERE code='C'), 'Curated Book Gift + Note', 'curated-book-gift-note', 'A book chosen just for you — because your CEO actually pays attention', 'Hand-selected book based on the recipient''s interests, paired with a handwritten note from the CEO explaining why this book was chosen for them. The gift that says ''I know who you are.''', 'Spot awards for the well-read and curious', 'A book chosen for you proves leadership was paying attention.', 7, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['paper'], ARRAY['print']::personalization_type[], ARRAY['spot_award']::occasion_type[], ARRAY['scholar','creator']::employee_archetype[], ARRAY['book','personal','leadership','desk-test'], 'standard', false, false, true, 7),
('NV-C08', (SELECT id FROM buckets WHERE code='C'), 'Leather Portfolio Embossed', 'leather-portfolio-embossed', 'Carry your ambitions in something worthy of them', 'Full-grain leather portfolio with debossed name and company logo. Document holder, card slots, pen loop. Executive daily carry that elevates every meeting.', 'Spot awards for rising executives', 'A daily-carry portfolio keeps recognition in hand at every meeting.', 8, NULL, NULL, NULL, NULL, NULL, 9, 5, 10, ARRAY['leather'], ARRAY['deboss']::personalization_type[], ARRAY['spot_award']::occasion_type[], ARRAY['achiever','scholar']::employee_archetype[], ARRAY['portfolio','leather','executive'], 'premium', false, false, true, 8),
('NV-C09', (SELECT id FROM buckets WHERE code='C'), 'CEO Video Stand QR+Acrylic', 'ceo-video-stand-qr-acrylic', 'A personal message from the top — press play', 'Elegant acrylic desk stand with embedded QR code linking to a personalised CEO video message. The physical frame stays on the desk; the emotional message plays on demand.', 'Spot awards that need a personal touch', 'A scannable message keeps the recognition alive long after the day.', 9, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['acrylic'], ARRAY['laser_engrave']::personalization_type[], ARRAY['spot_award']::occasion_type[], ARRAY['achiever']::employee_archetype[], ARRAY['digital','desk','leadership','desk-test'], 'standard', false, false, true, 9),
('NV-C10', (SELECT id FROM buckets WHERE code='C'), 'Premium Hamper 5-Item CEO', 'premium-hamper-5-item-ceo', 'The flagship CEO gift — five items, one unforgettable moment', 'Our most prestigious recognition gift. Curated 5-item experience kit including wax-sealed CEO letter, engraved copper bottle, achievement coin, premium notebook, and narrative card. Presented in a fabric-wrapped flagship box.', 'The highest-stakes leadership recognition', 'A layered reveal makes recognition feel like an event.', 10, NULL, NULL, NULL, NULL, NULL, 9, 5, 5, ARRAY['copper','paper','metal','fabric'], ARRAY['laser_engrave']::personalization_type[], ARRAY['spot_award']::occasion_type[], ARRAY['achiever']::employee_archetype[], ARRAY['hamper','flagship','leadership','desk-test'], 'flagship', false, false, true, 10),
('NV-C11', (SELECT id FROM buckets WHERE code='C'), 'Crystal Star Trophy 3D Laser', 'crystal-star-trophy-3d-laser', 'Stars belong on desks, not just in the sky', '3D laser-engraved crystal star trophy with the recipient''s name, achievement, and date suspended inside the crystal. LED base illuminates the engraving. A shelf centrepiece.', 'Spot awards for standout performers', 'A lit trophy keeps the win glowing on the shelf.', 8, NULL, NULL, NULL, NULL, NULL, 9, 5, 10, ARRAY['crystal','led'], ARRAY['laser_engrave']::personalization_type[], ARRAY['spot_award']::occasion_type[], ARRAY['achiever']::employee_archetype[], ARRAY['award','crystal','leadership','desk-test'], 'premium', false, false, true, 11),
('NV-C12', (SELECT id FROM buckets WHERE code='C'), 'Brass Desk Globe Name Base', 'brass-desk-globe-name-base', 'For the leader who thinks globally', 'Vintage-style brass desk globe on wooden base with engraved nameplate. A timeless executive desk piece that signals ambition and worldview.', 'Spot awards for big-picture leaders', 'A desk globe signals ambition without saying a word.', 8, NULL, NULL, NULL, NULL, NULL, 9, 5, 10, ARRAY['brass','wood'], ARRAY['laser_engrave']::personalization_type[], ARRAY['spot_award']::occasion_type[], ARRAY['achiever','explorer']::employee_archetype[], ARRAY['globe','brass','desk','desk-test'], 'premium', false, false, true, 12)
ON CONFLICT (sku) DO NOTHING;

-- ---------- Bucket D — Festive & Seasonal (NV-D05–NV-D15) -------------------
INSERT INTO products (sku, bucket_id, name, slug, tagline, description, who_is_it_for, insight, wow_score, cogs, price_single, price_bulk_25, price_bulk_100, margin_percent, lead_time_days, rush_lead_time_days, moq, materials, personalization_types, occasions, archetypes, tags, recommended_packaging, is_featured, is_bestseller, is_new, sort_order) VALUES
('NV-D05', (SELECT id FROM buckets WHERE code='D'), 'Holi Organic Colour Kit', 'holi-organic-colour-kit', 'Colours that care — for your skin and the planet', 'Organic, skin-safe Holi colour kit with 4 vibrant shades in reusable brass containers. Personalised pouch with team member name. Fun, festive, and eco-conscious.', 'Teams celebrating Holi together', 'Skin-safe and reusable makes a festive gift feel considered.', 6, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['brass','cotton'], ARRAY['print']::personalization_type[], ARRAY['custom']::occasion_type[], ARRAY['connector','creator']::employee_archetype[], ARRAY['festive','holi','eco-friendly'], 'standard', false, false, true, 5),
('NV-D06', (SELECT id FROM buckets WHERE code='D'), 'Christmas Acrylic Ornament', 'christmas-acrylic-ornament', 'Your name on the tree — your place in the team', 'Custom laser-cut acrylic Christmas ornament with employee name and year. Comes in a velvet pouch. A keepsake that returns to the tree every December.', 'Teams marking the festive year-end', 'A named ornament earns a yearly spot in the recipient''s home.', 6, NULL, NULL, NULL, NULL, NULL, 5, 3, 25, ARRAY['acrylic'], ARRAY['laser_engrave']::personalization_type[], ARRAY['custom']::occasion_type[], ARRAY['connector','creator']::employee_archetype[], ARRAY['festive','christmas','keepsake'], 'budget', false, false, true, 6),
('NV-D07', (SELECT id FROM buckets WHERE code='D'), 'New Year Custom Photo Calendar', 'new-year-custom-photo-calendar', '12 months of memories — personalised for your desk', 'Premium desk calendar featuring team photos, company milestones, and important dates. Each month tells a story. 12 months of brand visibility on every desk.', 'Teams starting the year together', 'A photo calendar keeps the team in view all year long.', 6, NULL, NULL, NULL, NULL, NULL, 5, 3, 25, ARRAY['paper'], ARRAY['print']::personalization_type[], ARRAY['new_year']::occasion_type[], ARRAY['scholar','connector']::employee_archetype[], ARRAY['calendar','desk','new-year','desk-test'], 'budget', false, false, true, 7),
('NV-D08', (SELECT id FROM buckets WHERE code='D'), 'Pongal Brass Thali Set', 'pongal-brass-thali-set', 'Harvest traditions, crafted in brass', 'Traditional brass thali set celebrating Pongal — culturally significant for South Indian teams. Engraved with recipient name. Heritage craftsmanship from Moradabad.', 'Teams honouring regional festive traditions', 'Honouring a regional festival makes recognition feel personal.', 7, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['brass'], ARRAY['laser_engrave']::personalization_type[], ARRAY['custom']::occasion_type[], ARRAY['root','achiever']::employee_archetype[], ARRAY['festive','pongal','brass','desk-test'], 'standard', false, false, true, 8),
('NV-D09', (SELECT id FROM buckets WHERE code='D'), 'Monsoon Care Kit Umbrella+', 'monsoon-care-kit-umbrella', 'Because someone thought about you when it rained', 'Seasonal care kit with premium compact umbrella, branded rain cover, and hot beverage sachet set. Personalised pouch. The surprise gift that arrives exactly when needed.', 'Teams through the monsoon season', 'A gift that arrives right on cue feels like genuine care.', 6, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['fabric'], ARRAY['print']::personalization_type[], ARRAY['custom']::occasion_type[], ARRAY['connector','root']::employee_archetype[], ARRAY['seasonal','care-kit','monsoon'], 'standard', false, false, true, 9),
('NV-D10', (SELECT id FROM buckets WHERE code='D'), 'Summer Hydration Kit Copper+', 'summer-hydration-kit-copper', 'Stay cool, stay hydrated, stay valued', 'Summer wellness kit with engraved copper bottle, infuser, and electrolyte sachets in a branded cooler pouch. Practical seasonal gifting that shows year-round care.', 'Teams through the summer months', 'Seasonal utility proves care is a year-round habit.', 7, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['copper','fabric'], ARRAY['laser_engrave']::personalization_type[], ARRAY['custom']::occasion_type[], ARRAY['root','achiever']::employee_archetype[], ARRAY['seasonal','wellness','hydration'], 'standard', false, false, true, 10),
('NV-D11', (SELECT id FROM buckets WHERE code='D'), 'IPL Fan Kit Tee+Mug', 'ipl-fan-kit-tee-mug', 'Team spirit meets team spirit', 'Cricket season celebration kit with custom team-themed t-shirt and mug. Designed for office IPL watch parties and team bonding moments.', 'Teams bonding over cricket season', 'Shared fandom turns a season into a team ritual.', 7, NULL, NULL, NULL, NULL, NULL, 5, 3, 25, ARRAY['cotton','ceramic'], ARRAY['dtf']::personalization_type[], ARRAY['custom']::occasion_type[], ARRAY['connector','creator']::employee_archetype[], ARRAY['cricket','team-spirit','kit'], 'budget', false, false, true, 11),
('NV-D12', (SELECT id FROM buckets WHERE code='D'), 'Festive Block Print Tote', 'festive-block-print-tote', 'Carry the festival home — in style', 'Hand block-printed cotton tote bag in festive patterns. Rajasthani artisan craft meets daily utility. Reusable, beautiful, and personalised with name tag.', 'Teams celebrating any festive occasion', 'A daily-carry tote keeps the festive sentiment in circulation.', 5, NULL, NULL, NULL, NULL, NULL, 5, 3, 25, ARRAY['cotton'], ARRAY['print']::personalization_type[], ARRAY['custom']::occasion_type[], ARRAY['creator','root']::employee_archetype[], ARRAY['festive','tote','artisan'], 'budget', false, false, true, 12),
('NV-D13', (SELECT id FROM buckets WHERE code='D'), 'Eid Gift Box Dates+Copper+', 'eid-gift-box-dates-copper', 'Eid Mubarak — with warmth and intention', 'Inclusive festive gift box with premium dates, copper serving bowl, and personalised greeting card. Celebrates Eid with the same care we bring to every occasion.', 'Teams celebrating Eid with intention', 'Inclusive festive gifting signals everyone belongs here.', 7, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['copper','paper'], ARRAY['laser_engrave']::personalization_type[], ARRAY['custom']::occasion_type[], ARRAY['root','connector']::employee_archetype[], ARRAY['festive','eid','gift-box','desk-test'], 'standard', false, false, true, 13),
('NV-D14', (SELECT id FROM buckets WHERE code='D'), 'Company Anniversary Memento', 'company-anniversary-memento', 'The company grew — and you grew with it', 'Custom-designed company anniversary memento combining the company''s milestone with the employee''s personal journey. Acrylic or metal, with key dates and achievements.', 'Whole teams marking a company milestone', 'Tying the company milestone to the person makes both matter more.', 7, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['acrylic','metal'], ARRAY['laser_engrave']::personalization_type[], ARRAY['company_anniversary']::occasion_type[], ARRAY['achiever']::employee_archetype[], ARRAY['memento','anniversary','keepsake','desk-test'], 'standard', false, false, true, 14),
('NV-D15', (SELECT id FROM buckets WHERE code='D'), 'Event Photo Strip Frame', 'event-photo-strip-frame', 'The offsite is over — the memory stays on your desk', 'Custom photo strip frame featuring event/offsite photos in a retro photo-booth style layout. Acrylic desk stand with event name and date.', 'Teams returning from an offsite or event', 'A desk photo strip keeps the offsite alive long after it ends.', 7, NULL, NULL, NULL, NULL, NULL, 5, 3, 25, ARRAY['acrylic','photo-paper'], ARRAY['print']::personalization_type[], ARRAY['team_offsite']::occasion_type[], ARRAY['connector','creator']::employee_archetype[], ARRAY['photo','desk','event','desk-test'], 'budget', false, false, true, 15)
ON CONFLICT (sku) DO NOTHING;

-- ---------- Bucket E — Client Appreciation (NV-E05–NV-E12) ------------------
INSERT INTO products (sku, bucket_id, name, slug, tagline, description, who_is_it_for, insight, wow_score, cogs, price_single, price_bulk_25, price_bulk_100, margin_percent, lead_time_days, rush_lead_time_days, moq, materials, personalization_types, occasions, archetypes, tags, recommended_packaging, is_featured, is_bestseller, is_new, sort_order) VALUES
('NV-E05', (SELECT id FROM buckets WHERE code='E'), 'Copper Decanter Set 2Glass+', 'copper-decanter-set-2glass', 'Pour the partnership a proper drink', 'Statement copper decanter with two glasses on a wooden tray. Name-engraved for the client who deserves more than a thank-you email. Moradabad heritage craftsmanship.', 'Key clients worth a memorable toast', 'A statement piece says the relationship matters more than the deal.', 9, NULL, NULL, NULL, NULL, NULL, 9, 5, 10, ARRAY['copper','wood'], ARRAY['laser_engrave']::personalization_type[], ARRAY['client_appreciation']::occasion_type[], ARRAY['achiever','connector']::employee_archetype[], ARRAY['barware','copper','client','desk-test'], 'flagship', false, false, true, 5),
('NV-E06', (SELECT id FROM buckets WHERE code='E'), 'Partnership Anniversary Crystal', 'partnership-anniversary-crystal', 'Milestones in crystal — for partnerships built to last', '3D laser-engraved crystal award celebrating partnership milestones. Both company logos, partnership duration, and key achievements etched inside. LED base included.', 'Long-standing client partnerships', 'Marking the partnership milestone signals you are in it for the long run.', 8, NULL, NULL, NULL, NULL, NULL, 9, 5, 10, ARRAY['crystal','led'], ARRAY['laser_engrave']::personalization_type[], ARRAY['client_appreciation']::occasion_type[], ARRAY['achiever']::employee_archetype[], ARRAY['award','crystal','partnership','desk-test'], 'premium', false, false, true, 6),
('NV-E07', (SELECT id FROM buckets WHERE code='E'), 'Desk Succulent Garden 3Plants', 'desk-succulent-garden-3plants', 'A living reminder of a growing partnership', 'Curated trio of desk succulents in engraved ceramic pots on a wooden tray. Low-maintenance living desk art that grows alongside the business relationship.', 'Clients you want to nurture over time', 'A living gift grows the relationship a little every day.', 7, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['ceramic','wood','plant'], ARRAY['laser_engrave']::personalization_type[], ARRAY['client_appreciation']::occasion_type[], ARRAY['creator','root']::employee_archetype[], ARRAY['plants','desk','living','desk-test'], 'standard', false, false, true, 7),
('NV-E08', (SELECT id FROM buckets WHERE code='E'), 'Client Spotlight Booklet Print', 'client-spotlight-booklet-print', 'Your partnership story — published and bound', 'Custom-designed booklet telling the story of the client partnership. Key milestones, shared achievements, and team photos. Magazine-quality printing. The partnership, immortalised.', 'Clients whose story is worth telling', 'A published story makes a partnership feel historic.', 10, NULL, NULL, NULL, NULL, NULL, 9, 5, 10, ARRAY['paper'], ARRAY['print']::personalization_type[], ARRAY['client_appreciation']::occasion_type[], ARRAY['achiever','scholar']::employee_archetype[], ARRAY['booklet','keepsake','partnership','desk-test'], 'premium', false, false, true, 8),
('NV-E09', (SELECT id FROM buckets WHERE code='E'), 'Premium Client Hamper 8-Item', 'premium-client-hamper-8-item', 'The flagship client gift — eight items of intention', 'Our most prestigious client gift. 8-item curated experience kit including copper decanter set, marble coasters, leather portfolio, artisanal tea, and more. Flagship packaging.', 'The most valued client relationships', 'A layered hamper makes the client feel like the priority.', 10, NULL, NULL, NULL, NULL, NULL, 9, 5, 5, ARRAY['copper','marble','leather','paper'], ARRAY['laser_engrave']::personalization_type[], ARRAY['client_appreciation']::occasion_type[], ARRAY['achiever']::employee_archetype[], ARRAY['hamper','flagship','client','desk-test'], 'flagship', false, false, true, 9),
('NV-E10', (SELECT id FROM buckets WHERE code='E'), 'Marble Visiting Card Holder', 'marble-visiting-card-holder', 'Cards held in marble — because first impressions are forever', 'Makrana marble visiting card holder with brass inlay and engraved client name. Jaipur-crafted desk piece that elevates the everyday act of exchanging cards.', 'Clients who value a refined desk', 'A desk piece used daily keeps your brand quietly present.', 7, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['marble','brass'], ARRAY['laser_engrave']::personalization_type[], ARRAY['client_appreciation']::occasion_type[], ARRAY['achiever','scholar']::employee_archetype[], ARRAY['marble','desk','executive','desk-test'], 'standard', false, false, true, 10),
('NV-E11', (SELECT id FROM buckets WHERE code='E'), 'Brass Pen Stand Engraved', 'brass-pen-stand-engraved', 'A pen deserves a throne — so does its owner', 'Solid brass pen stand with engraved nameplate. Classic executive desk accessory that brings weight and warmth to the daily writing ritual.', 'Clients who appreciate classic craft', 'A weighty desk classic earns a permanent place by hand.', 7, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['brass'], ARRAY['laser_engrave']::personalization_type[], ARRAY['client_appreciation']::occasion_type[], ARRAY['achiever','scholar']::employee_archetype[], ARRAY['brass','desk','executive','desk-test'], 'standard', false, false, true, 11),
('NV-E12', (SELECT id FROM buckets WHERE code='E'), 'Handcrafted Wood Box Pietra Dura', 'handcrafted-wood-box-pietra-dura', 'Heirloom-grade craftsmanship — a gift that outlives the deal', 'Handcrafted wooden box with pietra dura stone inlay work. Jaipur artisan tradition dating back to the Mughal era. A keepsake box that becomes a family heirloom.', 'Clients who appreciate heritage craft', 'An heirloom-grade gift outlives the deal that prompted it.', 9, NULL, NULL, NULL, NULL, NULL, 9, 5, 10, ARRAY['wood','marble'], ARRAY['laser_engrave']::personalization_type[], ARRAY['client_appreciation']::occasion_type[], ARRAY['achiever','creator']::employee_archetype[], ARRAY['heirloom','artisan','keepsake','desk-test'], 'flagship', false, false, true, 12)
ON CONFLICT (sku) DO NOTHING;

-- ---------- Bucket H — Sustainability & Eco (NV-H05–NV-H12) -----------------
INSERT INTO products (sku, bucket_id, name, slug, tagline, description, who_is_it_for, insight, wow_score, cogs, price_single, price_bulk_25, price_bulk_100, margin_percent, lead_time_days, rush_lead_time_days, moq, materials, personalization_types, occasions, archetypes, tags, recommended_packaging, is_featured, is_bestseller, is_new, sort_order) VALUES
('NV-H05', (SELECT id FROM buckets WHERE code='H'), 'Organic Soy Candle Named Tin', 'organic-soy-candle-named-tin', '40 hours of warm glow — with your name on it', 'Hand-poured organic soy wax candle in a reusable tin with the recipient''s name printed on the lid. 40-hour burn time. Natural essential oil fragrance.', 'Eco-conscious teams who value calm', 'A reusable tin keeps the gift useful long after the wax is gone.', 6, NULL, NULL, NULL, NULL, NULL, 5, 3, 25, ARRAY['soy-wax','metal'], ARRAY['print']::personalization_type[], ARRAY['custom']::occasion_type[], ARRAY['root','creator']::employee_archetype[], ARRAY['eco','candle','desk','desk-test'], 'budget', false, false, true, 5),
('NV-H06', (SELECT id FROM buckets WHERE code='H'), 'Recycled Fabric Tote Named', 'recycled-fabric-tote-named', 'Carry your values — literally', 'Tote bag made from recycled fabric with printed name and eco-message. Daily-carry visibility for sustainable living. Reinforced handles for everyday use.', 'Sustainability-minded daily commuters', 'A recycled daily-carry bag turns values into a habit.', 5, NULL, NULL, NULL, NULL, NULL, 5, 3, 25, ARRAY['cotton'], ARRAY['print']::personalization_type[], ARRAY['custom']::occasion_type[], ARRAY['root','creator']::employee_archetype[], ARRAY['eco','tote','sustainable'], 'budget', false, false, true, 6),
('NV-H07', (SELECT id FROM buckets WHERE code='H'), 'Compostable Packaging Set', 'compostable-packaging-set', 'Zero waste gifting — from box to earth', 'Complete zero-waste packaging option using compostable materials. Mushroom packaging, seed paper cards, biodegradable ribbon. For companies where sustainability is non-negotiable.', 'Companies where sustainability is non-negotiable', 'Packaging that returns to earth makes the whole gift credible.', 5, NULL, NULL, NULL, NULL, NULL, 5, 3, 25, ARRAY['seed-paper','paper'], ARRAY['print']::personalization_type[], ARRAY['custom']::occasion_type[], ARRAY['root','scholar']::employee_archetype[], ARRAY['eco','packaging','zero-waste'], 'budget', false, false, true, 7),
('NV-H08', (SELECT id FROM buckets WHERE code='H'), 'Tree-Planting Certificate Framed', 'tree-planting-certificate-framed', 'A tree planted in your name — growing while you work', 'Framed certificate confirming a real tree planted in the recipient''s name. QR code links to tree location and growth updates. Partnered with verified reforestation organisations.', 'Teams who want their impact to be real', 'A real tree makes a gift that keeps growing without a desk.', 7, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['paper','frame'], ARRAY['print']::personalization_type[], ARRAY['custom']::occasion_type[], ARRAY['root','achiever']::employee_archetype[], ARRAY['eco','certificate','desk','desk-test'], 'standard', false, false, true, 8),
('NV-H09', (SELECT id FROM buckets WHERE code='H'), 'Organic Cotton Tee Embroidered', 'organic-cotton-tee-embroidered', 'Soft on skin, gentle on the planet', 'GOTS-certified organic cotton t-shirt with embroidered name and company logo. Sustainable fashion that employees wear with pride and purpose.', 'Eco-conscious teams at onboarding', 'Certified fabric makes the sustainability claim believable.', 6, NULL, NULL, NULL, NULL, NULL, 5, 3, 25, ARRAY['organic-cotton'], ARRAY['embroidery']::personalization_type[], ARRAY['onboarding']::occasion_type[], ARRAY['root','connector']::employee_archetype[], ARRAY['eco','wearable','sustainable'], 'budget', false, false, true, 9),
('NV-H10', (SELECT id FROM buckets WHERE code='H'), 'Terracotta Planter Hand-Painted', 'terracotta-planter-hand-painted', 'Artisan earth — a living desk companion', 'Hand-painted terracotta planter by Bangalore artisans. Each piece unique. Comes with a starter plant and care card. Name tag attached with jute twine.', 'Teams who want a living desk piece', 'A living plant beats a plastic keepsake every single time.', 7, NULL, NULL, NULL, NULL, NULL, 7, 4, 25, ARRAY['terracotta','plant'], ARRAY['print']::personalization_type[], ARRAY['custom']::occasion_type[], ARRAY['creator','root']::employee_archetype[], ARRAY['eco','planter','desk','desk-test'], 'standard', false, false, true, 10),
('NV-H11', (SELECT id FROM buckets WHERE code='H'), 'Beeswax Wrap Set 3pc', 'beeswax-wrap-set-3pc', 'Wrap sustainably — at work and at home', 'Set of 3 beeswax food wraps in different sizes. Replaces plastic wrap. Printed with eco-tips and company branding. A daily-use reminder of sustainable values.', 'Teams cutting single-use plastic', 'A daily-use swap makes sustainability a habit, not a slogan.', 5, NULL, NULL, NULL, NULL, NULL, 5, 3, 25, ARRAY['beeswax','cotton'], ARRAY['print']::personalization_type[], ARRAY['custom']::occasion_type[], ARRAY['root','scholar']::employee_archetype[], ARRAY['eco','sustainable','zero-waste'], 'budget', false, false, true, 11),
('NV-H12', (SELECT id FROM buckets WHERE code='H'), 'Bamboo Cutlery Travel Set', 'bamboo-cutlery-travel-set', 'Your personal zero-waste kit — no more disposables', 'Bamboo fork, knife, spoon, chopsticks, and straw in a rolled cotton pouch. Engraved name on each piece. The everyday eco statement that replaces office disposables.', 'Teams ditching office disposables', 'A personal kit makes refusing disposables effortless.', 6, NULL, NULL, NULL, NULL, NULL, 5, 3, 25, ARRAY['bamboo','cotton'], ARRAY['laser_engrave']::personalization_type[], ARRAY['custom']::occasion_type[], ARRAY['root','scholar']::employee_archetype[], ARRAY['eco','travel','zero-waste'], 'budget', false, false, true, 12)
ON CONFLICT (sku) DO NOTHING;

-- =============================================================================
-- End of migration 005
-- =============================================================================
